### ISSUE TITLE
Update images

### ISSUE THREAD

**Issue by botte0** [eerotal/LibreSignage#100]
This might be a very specific and unusual question - but I am trying to use a Google Drawing that I published to the web as my image url on one of my slides. If I change the drawing, it changes the published image via the url. How often does libresignage update the image based on the url? Is there a way to change it so it makes sure it's got the most up-to-date image?

Thanks!

**Comment by botte0** [comment]
If I change the file on Google, it changes in the admin/editor console but it doesn't change on the actual display.

**Comment by botte0** [comment]
Sorry for the multiple posts! It seems like it's an issue with the site using the cached image instead of the new one. I think I have a workaround.

**Comment by tatusamma** [comment]
Would you mind posting the workaround, please?
