### ISSUE TITLE
Still having issues with attachments breaking

### ISSUE THREAD

**Issue by bandicootdancing** [eerotal/LibreSignage#110]
Running v1.1.0 after the last release announcement. Still having daily trouble with attachments breaking. Some days they break twice a day and I have to login and refresh the browser. We now have a second monitor in another area so I'm logging into two machines a a couple times a day to restart the browsers. 

I mentioned this in one of the other issues but a public slideshow without the need for login credentials would be nice in the meantime. I found some browser addons that load the page every x-hours but after a few logins the login page reappears. This might be a band aid fix for now.

**Comment by eerotal** [comment]
I guess I have some more debugging to do. Did the problem go away at all after the last fix? And just to confirm, are you starting a display session by selecting the checkbox on the login page? I'll probably implement a no login display at some point, however I want to get this issue properly fixed first.

**Comment by bandicootdancing** [comment]
It appeared to go away for a few days after upgrading to v1.1.0. For a while I thought it broke whenever I edited a slide or a slide expired but it started happening frequently after those first few days again where nothing was due to expire. At the moment I only have images but plan to add videos later on.  

No, slides haven't been started with the display session. Is there a difference between that and starting the slideshow from the display tab while normally logged in? I've set our locations up with display sessions. We'll see if that makes a difference.

**Comment by eerotal** [comment]
Display sessions never expire whereas normal sessions have a certain time after which they have to be renewed. The renewal is automatic so technically there should be no difference but if something goes wrong with the renewal the client will just log out.

**Comment by bandicootdancing** [comment]
So after about a week everything is still running as it should in both locations. Looks like starting as a display session was indeed the issue. Thanks for the help

**Comment by eerotal** [comment]
Great that it's working now. Be sure to tell me if you have any further problems.
