### ISSUE TITLE
iframe markup addition

### ISSUE THREAD

**Issue by evergrey** [eerotal/LibreSignage#112]
Great project. I am trying to do something similar to what someone was trying in issue#83 and add "iframe" support to markup. Iv tried tweaking the js to include an additional markup option of "iframe" based of your existing "img" tag in the source. I was tweaking the docker files as the build was giving me issues on UbuntuServer18LTS.
The following where the files i was adding my iframe code to but still getting "Unknown tag" in Editor and no iframe in Display.
/var/www/html/public/app/js/main.js
/var/www/html/public/control/editor/js/main.js

Could you point me in the right direction?

**Comment by eerotal** [comment]
Iframe tags are already implemented in `next` so they'll be included in the next minor release.

**Comment by evergrey** [comment]
Thanks for the quick reply. That is great news. I just built a native Ubuntu install to test out branch:next and it seems to be working perfectly. Appreciate the help.
