### ISSUE TITLE
Setting custom Quota

### ISSUE THREAD

**Issue by Qualitymix** [eerotal/LibreSignage#113]
I seem to be having trouble setting a custom quota.  I've searched around the Github and tried various solutions.  None of them seem to actually work.

I've tried adding a quota folder inside /var/www/localhost/config/conf and putting in a copy of the 00-defaults.php, renaming that to 01-custom.php, and changing the value.   
Doesn't work.  Is there a definitive way to change the quota?

**Comment by eerotal** [comment]
The `quota` directory should be in  `/var/www/localhost/config`, not in `/var/www/localhost/config/conf`. And in fact the directory doesn't need to be created since it exists by default.
