### ISSUE TITLE
Apache Alias Error 500 

### ISSUE THREAD

**Issue by comedian91** [eerotal/LibreSignage#117]
I want to call LibreSignage (Source Install with PHP 7.3 and Debian10) via an alias on Apache and not as DocumentRoot. If I set the DocumentRoot entry in the vHost file to a different directory and an alias to the path of LibreSignage, I get an Error 500 in the browser. Is there a way to use the application outside of DocumentRoot?

thank you in advance

**Comment by eerotal** [comment]
You should change the install directory while running `make configure` instead of manually editing the VirtualHost config. You can enter the install path when the script asks for `Install directory [default: /var/www]:`.

**Comment by comedian91** [comment]
Thanks for your reply. 

I ask my question differently 

I want to call LibreSignage as an alias. The login page should therefore only be loaded in the browser if e.g. example_site.net/projects/libresignage is called.
Your script always creates the install directory as DocumentRoot for the Apache Server, right? So when I call example_site.net I am always forwarded to the login page of libresignage and I would like to prevent this. Do you have any ideas how I could do this?

thank you in advance

**Comment by eerotal** [comment]
Ah, I'm not sure if that's possible with Apache since VirtualHosts only work on domain names but you can run LibreSignage under a subdomain if that's an option. It might also be possible to forward a path to a LibreSignage VirtualHost using an nginx or Apache reverse proxy but I haven't tried that myself so I'm not sure about that either.

**Comment by comedian91** [comment]
Thanks for your proposed solutions. I have now solved it by adding an additional virtualhost entry with an other port in the virtualhost config which points to the libresignage DocumentRoot. For example: 

```
> <VirtualHost *:80>
>     DocumentRoot "/var/www/"
>     ServerName name1
         ....
         ...
         ...
> </VirtualHost>
> 
> <VirtualHost *:8080>
>     DocumentRoot "var/www/apps/libresignage/public"
>     ServerName name1
         ..
         ..
> </VirtualHost>
```

this workaround fits for my test environment

Thank you for your efforts so far and great accomplishments in this project!

**Comment by eerotal** [comment]
Great that you got it working!
