### ISSUE TITLE
Error 500 after checkout the git working-dir 

### ISSUE THREAD

**Issue by comedian91** [eerotal/LibreSignage#118]
is there a way to use a perfectly working libresignage under e.g. /var/www/libresignage as a working directory for git so I can test/see a view changes directly on the browser?

Currently I get an Error 500 when I push from my local git repo to the test server and do a git checkout with a post-update hook to /var/www/libresignage.

with other words:
I have a working LibreSignage under /var/www/libresignage and copy the files into a new local git repo.
Change nothing there and push that back to the server and my post-update hook doing the checkout. Booom -> Error 500 instead of the Login Page.

the same thing happens when I download the files with e.g. WinSCP , delete the existing var/www/libresignage folder on the server and then upload it again.

Do I have to make the changes in the cloned git repo on the server and build a new libresignage with make -j $ (nproc) and make install?

Thank you in advance

**Comment by eerotal** [comment]
Yeah, you need to run `make -j $(nproc)` and then `make install` afterwards because there's a lot of code that's transpiled and you can't copy such code straight into /var/www/libresignage. You can of course add those commands to your post-update hook instead.
