### ISSUE TITLE
Problems uploading media files

### ISSUE THREAD

**Issue by gegge123** [eerotal/LibreSignage#119]
Hello everyone !
I just installed LibreSignage on my Linux machine which runs Debian Buster 10.1. When I want to upload media files from my local PC by clicking on the "Add media" choice underneath the Menu button
![Bildschirmfoto vom 2020-04-30 19-18-35](https://user-images.githubusercontent.com/33158688/80739918-93e52c80-8b17-11ea-8f0b-4f11de86d211.png) nothing happens.There are no files which can be selected, the area where the files or directories should show up is just empty. I supposed that the directory structure of my local PC will pop up and I can select the files I want to upload. The LibreSignage version is 1.1.0 . 

Thanks a lot in advance for your support !

**Comment by gegge123** [comment]
... just another screenshot ...
![Bildschirmfoto vom 2020-04-30 19-28-08](https://user-images.githubusercontent.com/33158688/80740772-e2df9180-8b18-11ea-84fc-97c14952e9d9.png)
which shows that nothing happens ...

**Comment by eerotal** [comment]
It appears you created a new slide so did you remember to save the slide first by clicking the save button at the bottom of the page? The editor won't let you upload media files into unsaved slides, so that might be the problem. I should definitely add a more clear indication of this to the UI.

**Comment by gegge123** [comment]
I just saved the slide before trying to upload media files. But it is the same behaviour, nothing happens, only an empty screen.

**Comment by eerotal** [comment]
Does the media upload dialog even let you open the file browser by clicking the browse button?

**Comment by gegge123** [comment]
No, when clicking on the Browse button there is no reaction. Only the tooltip pops up saying "No file chosen"

**Comment by eerotal** [comment]
Are you running one of the official Docker images or a self-built version? Does the browser developer console show any errors when you open the media upload dialog? I can't seem to be able to reproduce this issue for some reason.

**Comment by gegge123** [comment]
Maybe I can try to give You temporarily access to my installation if this helps ?

**Comment by eerotal** [comment]
Sorry for the delay. I can have a look if you give me access, although I wouldn't necessarily recommend opening up a LibreSignage instance to the whole internet especially without SSL.
