### ISSUE TITLE
Unable to generate API documentation

### ISSUE THREAD

**Issue by larseijman** [eerotal/LibreSignage#121]
This `http://[server_ip]/doc/?doc=api_index`route (from the help LS documentation) results in the following exception visible in plain HTML;
```
### Uncaught exception (HTTP: 404) ### Exception: No such documentation file. in /var/www/libresignage/public/doc/index.php:38 Stack trace: #0 {main}
```

When I try to generate the doxygen docs (with; `make doxygen-docs`) I get the following error:
```
...
Running dot for graph 331/332
Running dot for graph 332/332
Patching output file 1/155
error: problems opening map file /root/libresignage/original/LibreSignage/doxygen_docs/html/classlibresignage_1_1api_1_1APIException__inherit__graph.map for inclusion in the docs!
If you installed Graphviz/dot after a previous failing run, 
try deleting the output directory and rerun doxygen.
error: problems opening map file /root/libresignage/original/LibreSignage/doxygen_docs/html/classlibresignage_1_1api_1_1APIException__coll__graph.map for inclusion in the docs!
If you installed Graphviz/dot after a previous failing run, 
try deleting the output directory and rerun doxygen.
Patching output file 2/155
error: problem writing FIG 0 figure!
lookup cache used 2793/65536 hits=10793 misses=2857
finished...
```

Ubuntu 18.04 with `eerotal/LibreSignage:latest` clean install

**Comment by eerotal** [comment]
The API index documentation page was removed but I forgot to remove the link from the documentation index page. That's already fixed in the next major release though.

Please try installing graphviz by running `sudo apt install graphviz` to see if that fixes the error that you got while generating the Doxygen docs.

**Comment by larseijman** [comment]
Running `sudo apt install graphviz` fixed my error.
