### ISSUE TITLE
Multiple Screens

### ISSUE THREAD

**Issue by MoritzRauscher** [eerotal/LibreSignage#124]
Hey,
i have a little Question.
Is there an option to send different queues to different screens?

**Comment by eerotal** [comment]
Yes, you can select the queue that's displayed on each screen separately.

**Comment by MoritzRauscher** [comment]
Ok ty for the fast reply. :) How can i add Screens ?

**Comment by eerotal** [comment]
You just need to setup a machine to autostart a browser at boot and make it navigate to the LibreSignage display page. There some more info here: https://github.com/eerotal/LibreSignage/blob/master/src/doc/rst/display_setup.rst
