### ISSUE TITLE
How to automatically login to display?

### ISSUE THREAD

**Issue by MatthK** [eerotal/LibreSignage#132]
Hi

I just installed Libresign and setup a test slideshow and it is working. I then installed a Raspberry Pi and got it to boot automatically to start Libresign in kiosk mode. But I am struggling to have the Pi login automatically to actually display the slideshow instead of just the login screen.

How do you make the Raspi to log on automatically?

**Comment by eerotal** [comment]
When logging in on a display client for the first time, you should open the `> Advanced` tab on the login page and select `Start a display session.`. That prevents the display from logging out when the browser is closed, so it should automatically login on reboots.

**Comment by MatthK** [comment]
Ok, that worked. Thanks.
