### ISSUE TITLE
Changing passwords does not work

### ISSUE THREAD

**Issue by MatthK** [eerotal/LibreSignage#133]
I've been trying to change the passwords of existing default users, but whenever I enter the password twice and try to hit the save button, nothing happens. It simply does not save it. When checking the console, it states an 

`Uncaught (in promise) TypeError: e.get_code is not a function`

It does work though on a user that has admin rights.

**Comment by eerotal** [comment]
This is a known bug that's fixed in the next branch but that fix is not included in the latest stable yet.
