### ISSUE TITLE
Terminal access shutsdown the container

### ISSUE THREAD

**Issue by MatthK** [eerotal/LibreSignage#135]
Hi

I have LibreSignage installed on a Synology NAS. While it works fine so far, I can't attach the volume as the GUI only allows to mount a volume. If I do that, I'm having the same [problem as here](https://github.com/eerotal/LibreSignage/issues/126). 

So I thought I would try the approach suggested in the [Synology NAS forum](https://www.synoforum.com/threads/volume-on-syno-docker.3515/#post-16391). 

But every time I try to access the terminal, the container shutsdown gracefully. How can I access the terminal in that container?

```
root:/volume1/@docker/volumes# docker container attach a47c525b6b95
[Mon Jul 20 09:52:31.132800 2020] [mpm_prefork:notice] [pid 1] AH00170: caught SIGWINCH, shutting down gracefully
root:/volume1/@docker/volumes#

```

**Comment by eerotal** [comment]
You can access the terminal by running `docker exec -it <container> /bin/bash`, just replace <container> with the container ID. I think the suggestion in the thread you linked should work, but if you have problems with it you can also download the .zip of this GIT repo which includes the default data files. When you unzip the archive, the default files are in `src/data/`. You can just copy the contents of that directory to the mount point on your NAS. That should also work.

This whole thing is on my TODO list. I'm going to implement a system that automatically copies/writes the default files into the data directory if it's empty. That might take some time though.

**Comment by MatthK** [comment]
Using ssh I managed to get the terminal access with `docker exec -it <container> /bin/bash`. 

I managed to copy the files over and after I had updated the owner/group and permission of the files, it worked to login.

**Comment by MatthK** [comment]
I was a bit too optimistic. After some more testing, I realized, it's not really working. The whole system is a big mess and I guess it got somehow screwed up big time. I will delete it and start all over again.
