### ISSUE TITLE
Image is not displayed

### ISSUE THREAD

**Issue by ShadowGamb** [eerotal/LibreSignage#138]
Hi errotal,

first of all, thanks for your amazing software. I have two Ubuntu VMs, one for running LibreSignage, the other one is just for checking if everything is alright. My problem is, that LibreSignage won't show any pictures in my browser on my VM that is supposed to check. I have a screenshot attached.
![Capture](https://user-images.githubusercontent.com/45771418/88815884-1f746500-d1bc-11ea-840c-5b7d97b471de.PNG)

**Comment by eerotal** [comment]
Do you mean images embedded in slides don't work or do none of the images in the web interface load? Are you running the Docker image or a version that's manually built from sources? Do you use a reverse proxy in front of the server? Have you done any other custom configuration?

**Comment by ShadowGamb** [comment]
The embedded images don't work. I am running a version that's manually built from sources. No i don't use a reverse proxy. Same with custom configuration.

**Comment by ShadowGamb** [comment]
When i try the preview or the "View queue"-Button on the host, everything works, until i log in from another machine through the browser with any user.

**Comment by eerotal** [comment]
Aha! Did you access the web interface on the host machine at `http://localhost/`? If that's what you did, when you added the image to the slide the URL was automatically generated to have `http://localhost/` as the hostname. That won't work from any other machine, however. Try accessing the web interface from the IP that external machines can also access and re-copy the image URLs from the media uploader window. That should make it work.

**Comment by ShadowGamb** [comment]
Yes, now it works, thank you.
