### ISSUE TITLE
Popups not working

### ISSUE THREAD

**Issue by burfbari** [eerotal/LibreSignage#141]
Hi,

A few windows have stopped loading... 
Windows which are popup based, such as:-
- Queue Selector
- Media Uploader
- Live Preview
- Slide Scheduling

What could I have done? :)

**Comment by eerotal** [comment]
Does the developer console show any errors? You can open it in Firefox and Chrome by pressing F12 and selecting the Console tab.

**Comment by burfbari** [comment]
I checked it in the Console, but there are no errors there.

**Comment by burfbari** [comment]
A screenshot in case it might help

![89382921-3c0f2080-d719-11ea-8578-8cf79421621b](https://user-images.githubusercontent.com/52349056/89382921-3c0f2080-d719-11ea-8578-8cf79421621b.png)

**Comment by burfbari** [comment]
Thank you for your efforts and I appreciate it (and the questions). 


    What browser are you using and did the popups work previously?
----> I tried on Firefox and Chrome both and yes they worked pretty well.
    
    Were there any changes to the system between when the popups worked and when they stopped working?
-----> I did some changes but the popups worked even after those. It is just that one fine morning I got up to find they were not working.

    How are you running the LibreSignage instance, ie. are you running the Docker images or a self built version?
-----> Docker image

    What commands do you use to start the server?
------> I do not even know how to stop/start the LibreSignage server :)

**Comment by burfbari** [comment]
I guess it was due to renaming of the some folder...
