### ISSUE TITLE
Custom configuration file not working

### ISSUE THREAD

**Issue by burfbari** [eerotal/LibreSignage#142]
Hi,

Just to make sure that I have not messed up my installation as described in issue #141, I created a brand new Docker based installation on a new VM instance.

The first thing that I want to do is to increase quota of slides.

This is how my directory looks like

```
/var/lib/docker/overlay2/abcdef/merged/var/www/html/config/quota/
total 12
-rw-rw-r-- 1 999 docker 554 Jan 12  2020 00-default.php
-rw-r--r-- 1 999 docker 554 Aug  3 13:42 01-custom.php
-rw-r--r-- 1 999 docker 554 Jan 12  2020 02-default.php
```

This is how the `01-custom.php` looks like
```
<?php

/*
*  Default LibreSignage quota config. Don't edit this file directly.
*  Create a custom quota override file in conf/quota/ instead.
*/
return [
           // Quota for the maximum number of slides per user.
           'slides' => [
                      'limit' => 20,
                      'description' => 'Slides'
           ],
          // API rate limiting quota. The limit is in calls/API_RATE_T which
         // is calls/60s by default. You can find the API_RATE_T constant
         // in the config file, although you probably don't want to change it.
         'api_rate' => [
                      'limit' => 500,
                      'description' => 'API rate quota'
          ]
];
```

However, the changes do not reflect on the interface.

![screenshot-52 60 242 29-2020 08 05-12_14_43](https://user-images.githubusercontent.com/52349056/89381036-2f3cfd80-d716-11ea-931f-6cc543013c49.png)

Please help!
Thank you.

**Comment by burfbari** [comment]
[https://nimb.ws/MFKn3r](url)

**Comment by eerotal** [comment]
The config files are read and processed in the order indicated by the file numbering, ie. 00-default.php is read first, 01-custom.php is read second and 02-default.php is read last. Does your 02-default.php file contain the default config without the changes to the quota? If that's the case, the default config will override you custom config from 01-custom.php because it's read last.

**Comment by burfbari** [comment]
Thank you for the clarification. It works!
