### ISSUE TITLE
Error while changing Password

### ISSUE THREAD

**Issue by burfbari** [eerotal/LibreSignage#143]
Hi,

I am seeing the following error while trying to unsuccessfully change the password.

     Uncaught (in promise) TypeError: e.get_code is not a function
       handle_error https://xxxx/control/user/js/main.js:20103
       save_password https://xxxx/control/user/js/main.js:20066

Please suggest. Thank you.

**Comment by eerotal** [comment]
This is a known bug that's fixed in the next branch but that fix is not included in the latest stable yet. Until the next version is released, you should create new users instead of changing passwords as a workaround.
