### ISSUE TITLE
Cannot save slide

### ISSUE THREAD

**Issue by mauro2306** [eerotal/LibreSignage#144]
Hello,

as wrote in another issue : https://github.com/eerotal/LibreSignage/issues/74#issuecomment-678733732
i am currently using libresignage to replace the digital menu on screen of the fast food of my parents. As i am not able to get the columns with custom size (the one for the price should be smaller of course), i tried to "hack" a bit the current possibilities to get my way. The preview within the editor looks good, shows all entry but i can't save, nothing happens when i try to do so, and i try to look in the logs but wasn't able to find any errors. this is how does look my editor, i don't find the error.
`
[container top=12% right=5% bottom=0% left=4%]
    [bgimg url="https://&hash="][/bgimg]
    [align type=left]
	   	[h size=12%][color c=snow][b]Family Burger[/b][/color][/h]
    [/align]
[/container]
[container top=0% right=1% bottom=1% left=2%]
	[columns]
		[container top=1% right=1% bottom=1% left=1%]
		    [h size=5%][color c=yellowgreen][b]Pitta - Durum[/b][/color][/h]
		
	        [container top=1% right=1% bottom=1% left=1%]
			    [h size=3%]
                [align type=left][b]
		        PITTA POCHE[color c=white]...................................[/color]4.80
		        PITTA GRECQUE[color c=white].............................[/color]7.00
		        KEBAB FAMILY[color c=white]................................[/color]6.00
		        DURUM[color c=white]................................................[/color]5.00
		        DURUM VÉGÉTARIEN[color c=white]..................[/color]4.50
		        PITTA GÉANTE FRITE[color c=white]..................[/color]12.00
		        SUPPLÉMENT - FETA \/ FRITE[color c=white]....[/color]1.00
		        ANANAS - OLIVES[color c=white]..........................[/color]0.50
	            CRUDITÉS[color c=white]..........................................[/color]0.30
                [/b][/align]
			    [/h]
		    [/container]
		        
		[/container]
		[container top=1% right=1% bottom=1% left=1%]
			[h size=5%][color c=yellowgreen][b]Frites[/b][/color][/h]
		    		[container top=1% right=1% bottom=1% left=1%]
			        [h size=3%]
			        [align type=left][b]
			        JUNIOR[color c=white].................................................[/color]1.60
			        PETITE[color c=white]..................................................[/color]2.20
			        MOYENNE[color c=white]..........................................[/color]2.40
			        GRANDE[color c=white]..............................................[/color]2.70
			        [/b][/align]
			        [/h]
			        [h size=5%][color c=yellowgreen][b]Sauces chaudes[/b][/color][/h]
			        [h size=3%]
			        [align type=left][b]
			        BÉARNAISE[color c=white]........................................[/color]1.50
			        CHAMPIGNON[color c=white]..................................[/color]1.50
			        POIVRE[color c=white].................................................[/color]1.50
			        [/b][/align]
			        [/h]
		            [/container]
		[/container]
		[container top=1% right=1% bottom=1% left=1%]
			[h size=5%][color c=yellowgreen][b]Salades[/b][/color][/h]
		        [container top=1% right=1% bottom=1% left=1%]
			        [h size=3%]
			        [align type=left][b]
			        VÉGÉTARIENNE[color c=white]...............................[/color]5.00
			        GRECQUE[color c=white]............................................[/color]7.00
			        THON[color c=white].....................................................[/color]7.00
			        POULET[color c=white]................................................[/color]7.00
			        MEDITÉRANÉENNE[color c=white].......................[/color]7.00
			        MAISON[color c=white]................................................[/color]7.00
			        [/b][/align]
			        [/h]
			        [h size=5%][color c=yellowgreen][b]Pâtes[/b][/color][/h]
			        [h size=3%]
			        [align type=left][b]
			        BOLOGNAISE PETITE[color c=white]...................[/color]4.80
			        BOLOGNAISE GRANDE[color c=white]...............[/color]7.00
			        4 FROMAGES PETITE[color c=white]....................[/color]7.00
			        4 FROMAGES GRANDE[color c=white]...............[/color]7.00
			        LASAGNE[color c=white]............................................[/color]7.00
			        [/b][/align]
			        [/h]
		        [/container]
		[/container]
	[/columns]

[/container]
`
![Capture d’écran 2020-08-23 à 19 43 42](https://user-images.githubusercontent.com/69889380/90984985-040d3780-e579-11ea-971d-9a33aba19e2c.png)

thanks for the help.

**Comment by eerotal** [comment]
Someone reported in #139 that the save button doesn't work until you reload the page but they haven't responded to my message after that so I haven't been able to debug the issue. Have you tried reloading the page? You can even try a forced reload by pressing Ctrl+F5. Are you able to save any other slides with less complex markup?

**Comment by mauro2306** [comment]
Thanks for the feedback. Of course you can reload the page, but then you loose the changes you made. Saving a page with less complex markup does work without any issue indeed. 
The error i am having in the browser console is the following :

```
XHRPOSThttps://****/api/endpoint/slide/slide_save.php
[HTTP/2 400 Bad Request 124ms]

	
POST
	https://****/api/endpoint/slide/slide_save.php
État400
Bad Request
VersionHTTP/2
Transfert5,07 Ko (taille 0 o)

    	
    cache-control
    	no-cache, private
    content-length
    	0
    content-type
    	application/json
    date
    	Fri, 28 Aug 2020 08:12:20 GMT
    server
    	nginx/1.18.0
    X-Firefox-Spdy
    	h2
    x-powered-by
    	PHP/7.2.26
    	
    Accept
    	*/*
    Accept-Encoding
    	gzip, deflate, br
    Accept-Language
    	fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
    Auth-Token
    	5****
    Connection
    	keep-alive
    Content-Length
    	4399
    Content-Type
    	application/json
    Cookie
    	session_token=****
    DNT
    	1
    Host
    	****.be
    Origin
    	****.be
    Referer
    	https://****/control/editor/
    TE
    	Trailers
    User-Agent
    	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0
```


```
Uncaught (in promise) TypeError: e.get_code is not a function
    handle_error https://****/control/editor/js/main.js:226635
    save_slide https://***/control/editor/js/main.js:226522
    click https://***/control/editor/js/main.js:226052
    UIElem https://***/control/editor/js/main.js:230564
    dispatch https://***/control/editor/js/main.js:66041
    handle https://***/control/editor/js/main.js:65848
main.js:226635:8
    UIElem https://***/control/editor/js/main.js:230569
    (Asynchrone : promise callback)
    UIElem https://****/control/editor/js/main.js:230568
    dispatch https://****/control/editor/js/main.js:66041
    handle https://****/control/editor/js/main.js:65848

```

**Comment by eerotal** [comment]
Sorry for the late response. I think this is a problem with the markup itself. Currently the API only accepts letters a-z, numbers 0-9 and some other characters. Your markup contains letters such as É, which probably causes the error you're seeing. For now, you can try removing all those "special" characters and try to save the slide to see if it works. This is obviously something I need to fix since there are a lot of languages with a non-english alphabet.

**Comment by mauro2306** [comment]
> Sorry for the late response. I think this is a problem with the markup itself. Currently the API only accepts letters a-z, numbers 0-9 and some other characters. Your markup contains letters such as É, which probably causes the error you're seeing. For now, you can try removing all those "special" characters and try to save the slide to see if it works. This is obviously something I need to fix since there are a lot of languages with a non-english alphabet.

Hi,

no problem at all about the delay. My bad, i forgot to mention that i tried as well without these special characters, it wasn't working better unfortunately.

**Comment by eerotal** [comment]
Ah, that wasn't the issue after all. It seems the problem is with the default markup length limit set in the LibreSignage limits config file. The default maximim length is 2048 characters but you can safely increase that a lot by following the instructions here: https://github.com/eerotal/LibreSignage/blob/master/src/doc/rst/configuration.rst. In fact, you can even use the non-english characters aswell. Those shouldn't cause any problems.

**Comment by mauro2306** [comment]
Awesome, it worked fine, thanks. 
In order to not have to put these "...." to simulate a column, what do you think about improvement https://github.com/eerotal/LibreSignage/issues/74#issuecomment-678733732 ?
That would really be a great one.
Thanks.

**Comment by mauro2306** [comment]
Solved by increasing the "SLIDE_MARKUP_MAX_LEN" in limits config
