### ISSUE TITLE
Users without admin privilege can't change password

### ISSUE THREAD

**Issue by mauro2306** [eerotal/LibreSignage#145]
Hello,

if you try to change your password as non-admin user, you can type a new password but when trying to save it, nothing happens.
It is very annoying because you have to give the user the admin privilege, wait that he changes his password and then remove the privilege.

**Comment by eerotal** [comment]
This is a known bug (see #116) that's fixed in the next branch but that fix is not included in the latest stable yet. Until the next version is released, you should create new users instead of changing passwords or give temporary admin permissions as a workaround.
