### ISSUE TITLE
purpose built distro for LibreSignage

### ISSUE THREAD

**Issue by geeseven** [eerotal/LibreSignage#149]
Greetings,

I recently stumbled on this project and it looks very useful.  While currently I do not have a use for it myself, I wonder if I have seen it in the wild and not known it.  

I am curious if y'all have considered a purpose built distribution for LibreSignage.  Projects like [Kodi][0] have [LibreELEC][1] to turn an old PC or Raspberry Pi into a media center **appliance**.  I think that LS could benefit from a distribution that is pre-configured to use LS.  No messing with installing and configuring a LAMP stack and then installing LS. 

I am most familiar with LibreELEC, but I also have dabbled with [Lakka][2] and [OctoPi][3].  They all have some sort of plugin within the core application to deal with system setting, updates, backup and what not.

All that being said, I recognize that this is a big ask for someone that is not using your software.  In addition, most of the application focused distributions are maintained by a different group than the core application.  I hope this 'request' might inspire someone to look into creating a LS distribution. 

[0]: https://kodi.tv/
[1]: https://libreelec.tv/about/
[2]: https://www.lakka.tv
[3]: https://github.com/guysoft/OctoPi

**Comment by eerotal** [comment]
Yeah, this is certainly something I won't even look into as it's simply too much work to maintain a distro just for the purpose of distributing LibreSignage.
