### ISSUE TITLE
Login via app_bootstrap - screen stays blanc

### ISSUE THREAD

**Issue by fox27374** [eerotal/LibreSignage#151]
Hi,

I got the LS server running on a RaspberryPi Zero W (Arch Linux) within the Docker container. Administration works fine (a little bit slow, but thats the RPi I guess). When the browser starts in kisok mode, I configured it to open the following URL:

`http://localhost/app_bootstrap?user=display&queue=avhaus`

where "avhaus" is the name of my queue. I added the passwordless user "display" and added it to the collaborators of the queue.
After the browser starts, the screen stays blanc. All white, nothing is displayed. Am I doing something wrong here?
Thanks for the help!

**Comment by eerotal** [comment]
Did you remember to add your passwordless user to the "display" group?

**Comment by fox27374** [comment]
Hi, yes, the user "display" is in the display group. I tried with different users as well. Still the same behavior.

**Comment by fox27374** [comment]
I created a new passwordless user (not the display user) and it seems to work now, at least with the Chrome browser. Midori shows me a selection windows for the queue even if I have "&queue=avhaus" in the URL, but I guess thats a browser problem. I will keep you posted.

**Comment by fox27374** [comment]
It was a browser issue on the Raspberry Pi. Midori does not seem to work. With Epiphany the site is accessable
