### ISSUE TITLE
Passing queue to app_bootstrap

### ISSUE THREAD

**Issue by martinlanger90** [eerotal/LibreSignage#154]
I'm trying to pass the queue, but that does not work in any way I try it

http://localhost/app_bootstrap?user=monitor?queue=default 

http://localhost/app_bootstrap?user=monitor/?queue=default 

http://localhost/app_bootstrap/?user=monitor?queue=default 

http://localhost/app_bootstrap/?user=monitor/?queue=default 

I'm either getting to a blank page or to the "Select a queue" page.

How to solve?! 

thank you

**Comment by JonnyTech** [comment]
The ampersand character is usually used to link paremeters, ie:

http://localhost/app_bootstrap/?user=monitor&queue=default

**Comment by martinlanger90** [comment]
Thank you. I could have known this myself (stupid...)
Great. Now it's working.
