### ISSUE TITLE
What happens when player or display drops or loses internet connection

### ISSUE THREAD

**Issue by bossbarnes07** [eerotal/LibreSignage#25]
What happens when player or display drops or loses internet connection

**Comment by eerotal** [comment]
When a client loses internet connection an error dialog pops up, and now that I think about it I should handle it a bit better. Right now the dialog would have to be closed manually.

**Comment by bossbarnes07** [comment]
Thanks you

**Comment by eerotal** [comment]
LibreSignage uses web browsers as clients and AFAIK most mainstream browsers support caching. LibreSignage itself doesn't download the content onto the client system though, so all caching is handled by the browser. Now, I haven't actually paid much attention to how various HTTP requests are cached yet, so I'll probably have to investigate that a bit too.

**Comment by bossbarnes07** [comment]
Thanks for responding. I attempting to build a server for testing. But something is wrong I'm only able to get the Apache2 Ubuntu Default Page. Can your please enlighten me on the problem.  The Host file has the following IP info
127.0.0.1 Localhost
127.0.1.0 Name of Server.  Thanks

**Comment by eerotal** [comment]
No problem. Just to clarify, are these the commands you ran after installing the required dependencies and did all of them run without any errors?

  make configure
  make
  sudo make install

If that's correct, here are some things you can check:

1. If you set "localhost" or the LAN IP of your machine as the server name when `make configure` asked for it, you don't need to add anything into `/etc/hosts`. The server *should* work just by navigating to localhost or the configured IP. 
2. You can check if the directory where you installed LibreSignage contains any files. The exact path varies depending on how you configured the installation, but by default it's in `/var/www/<server name>` where <server name> is the server name you gave when `make configure` asked for it.
2. You can check whether the Apache virtual host is enabled. If it is, there should be a file named `<server name>.conf` in `/etc/apache2/sites-enabled`. Again, <server name> is the same thing as before.

**Comment by bossbarnes07** [comment]
I think I may have found the problem. My server is Ubuntu 18.04 LTS 64Bit. The error I obtain after install npm is attached below. Again thank you for help thus far.

![libresignage](https://user-images.githubusercontent.com/44912379/48975637-8171e400-f043-11e8-8939-470749f158d8.PNG)

**Comment by eerotal** [comment]
Ah, that warning is actually normal and it doesn't cause any problems. I get it on my systems too. Did you check the other things in my previous comment?

**Comment by felix-wo** [comment]
> Thanks for responding. I attempting to build a server for testing. But something is wrong I'm only able to get the Apache2 Ubuntu Default Page. Can your please enlighten me on the problem. The Host file has the following IP info
> 127.0.0.1 Localhost
> 127.0.1.0 Name of Server. Thanks

On Ubuntu 18.04 try disabling the pre-installed site showing the default page you’re getting:
`# as root or via sudo:`
`a2dissite 000-default.conf`
`systemctl apache2 restart   # reload apache config`

**Comment by bossbarnes07** [comment]
Okay I think i got it working but I'm having display problem with the URL. When I attempt to access front-end I get the followng: Thanks for your help. If possible what OS and version should I use

![image](https://user-images.githubusercontent.com/44912379/49664467-fcfa6a80-fa1f-11e8-988e-0b415f8fe7d8.png)

**Comment by eerotal** [comment]
Ah yes. I have fixed quite a lot of bugs in the last few days and that error was one of them. You can clone the 0.2.2-dev branch which contains the bugfixes. At least Debian 9 (Stretch) and Debian 10 (Buster, still in testing though) work. Ubuntu probably works too but I haven't tested it myself.

**Comment by bossbarnes07** [comment]
Thanks for the update and info, I'm new to git hub. I was able to fine the 0.2.2-dev under branch but I'm not sure how to clone it the link look the same as the one for master. I'm sorry to bother you but could you please provide details. I'm assuming that when I pick the branch everything is updated on the page for the selected branch.

**Comment by eerotal** [comment]
Sure. You just need to move into the directory where you originally cloned LibreSignage and then run the following commands:

```
git pull
git checkout v0.2.2-dev
make clean
make configure
make -j$(nproc)
sudo make install
```

These commands will pull the new changes, rebuild LibreSignage and install the new version. And yes, when you select a branch on the GitHub page, you see the updated readme for the selected branch.

**Comment by bossbarnes07** [comment]
eerotal,
I another problem. The webpage looks fine but it will not allow me to login with either of the IDs. Please advise.

**Comment by eerotal** [comment]
That's odd. Does the login page show any error messages or does it just tell the username/password are invalid? What Linux distro and version are you using?

**Comment by bossbarnes07** [comment]
I'm using ubuntu 18.04 x64 no error message screen shot below.
![image](https://user-images.githubusercontent.com/44912379/49699452-56d56e80-fb9f-11e8-9b15-5b3a2d790ac8.png)

**Comment by felix-wo** [comment]
@bossbarnes07 Your LibreSignage instance isn’t installed properly yet, obviously. I had a similar appearance (without proper CSS, as you have right now!) and couldn’t login either (see #26). I got it running on Debian 9.6.

@eerotal As I already said, I think, a installation guide for a specific OS, maybe Debian Stretch, should be provided, really step by step and even specifying the used version (e.g. netinstall) for the OS. If you want, I will go through an installation of it on Debian again, note everything, and post it here. I also could try an installation on Ubuntu.

**Comment by eerotal** [comment]
> I'm using ubuntu 18.04 x64 no error message screen shot below.

The login screen should have CSS styling when it's installed correctly, so something is still wrong with the installation. As @felix-wo also said, I'd try deleting the repo directory where you cloned LibreSignage and the install directory, which is in `/var/www/<domain name>` by default. Then you can try the installation process again.

> @eerotal As I already said, I think, an installation guide for a specific OS, maybe Debian Stretch, should be provided, really step by step and even specifying the used version (e.g. netinstall) for the OS. If you want, I will go through an installation on Debian again, note everything, and post it here. I also could try an installation on Ubuntu.

Yeah, the installation instructions could probably still be improved, although I think the updated instructions in v0.2.2-dev *should* work quite smoothly. Specifying the Debian/Ubuntu etc. version is a good idea too, although whether netinstall or some other image variant is used doesn't really matter since in the end the distro is exactly the same.

But sure, If you want you can go through the installation to see if there's something to add to the instructions.

**Comment by felix-wo** [comment]
Agree – _should_ work quite smoothly. And indeed, it’s important to change to the [v0.2.2-dev branch on the github page for the instructions](https://github.com/eerotal/LibreSignage/tree/v0.2.2-dev), too.

> […] whether netinstall or some other image variant is used doesn't really matter since in the end the distro is exactly the same.

Should be the case, yes … I’m not sure though, if the same selection of packages are installed by default or, respectively, if the same possibilities of selections are available in different installers.

So let’s do it! Writing down, what I’m doing, so others can reproduce.

**Installing LibreSignage v0.2.2-dev on Debian Stretch (ver. 9.6)**

Taking [debian-9.6.0-amd64-netinst.iso](https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-9.6.0-amd64-netinst.iso) for installation (may get outdated quickly, newer subversions of Debian Stretch will follow – but it shouldn’t matter, as the software versions delivered with Debian 9 should never change)

(I’m installing it on a KVM host running Ubuntu 16.04; I’ve also successfully tried on VirtualBox  5.2 on Ubuntu 18.04 host; on which virtualizer and which host you put it to, or if you choose bare metal, shouldn’t matter at all.)

I give the VM just 1 CPU core and 1 GiB of RAM. 5 GiB hard drive should be plenty, if you don’t use the system for further applications than LibreSignage and if you don’t upload massive amounts of media files on it.

Boot from the ISO. Choose "Install" ("Graphical install" works the same way – have tested it, too), follow the installer, i.e. choose language etc., set a hostname (e.g. "libresignage"), set your domain name (if available), setup user accounts (root and standard user), set time zone. Partitioning: Put everything just on one partition for simplicity, just as the installer suggests. Further steps: Normally just take the default suggestions. Software selection: just "standard system utilities" (uncheck "Debian desktop environment" and "print server"). Let it install GRUB bootloader, normally just on the one and only partition, as created just before. Installation finishes, let it reboot (may be necessary to prevent the VM from booting the ISO again). Login as root.

`apt update && apt full-upgrade -y` (On netinstall all packages should be up to date, anyway.)
`apt install git apache2 php php-gd ffmpeg pandoc make curl` (install dependencies)
`curl -sL https://deb.nodesource.com/setup_11.x | bash - && apt-get install -y nodejs` (install nodejs as well)
`cd`
`mkdir git` (create download directory for git)
`cd git`
`git clone https://github.com/eerotal/LibreSignage.git`
`cd LibreSignage`
`git checkout v0.2.2-dev`
`npm install`
`make configure` (and put in the information it asks for)
`make`
`make install` and answer "y" to all the 3 questions
`a2dissite 000-default.conf` (disable the default apache host)
`systemctl reload apache2`

Open host address in browser, login to LibreSignage.

**Comment by eerotal** [comment]
> And indeed, it’s important to change to the v0.2.2-dev branch on the github page for the instructions, too.
That's the case for now, yes. After v0.2.2 is released the new instructions will be visible in the master branch too.

Anyway, these are great. Thanks! So the installation works without any problems on Ubuntu as well? Actually, there doesn't seem to be any major differences between installation on Debian and Ubuntu as far as I can see. Is that correct? I'll add some of this info to the readme, although I'm not convinced about adding VM setup or OS installation instructions to LibreSignage docs since those might get outdated and I'd have to keep track of them too.

**Comment by felix-wo** [comment]
> > And indeed, it’s important to change to the v0.2.2-dev branch on the github page for the instructions, too.
> 
> That's the case for now, yes. After v0.2.2 is released the new instructions will be visible in the master branch too.

That’s clear – but maybe worth mentioning.

> Anyway, these are great. Thanks! So the installation works without any problems on Ubuntu as well?

Yes, it does! At least as far as I’ve tested the application so far. Tell me if I should test out something specific. I’ll just do my further testing on the Ubuntu installation, so I’ll gain experience with it.

> Actually, there doesn't seem to be any major differences between installation on Debian and Ubuntu as far as I can see. Is that correct?

Yes, exactly. That’s what I wanted to figure out. Ubuntu Server has just some packages installed already per default, nodejs is installed from a PPA in both of my scenarios. Nothing unexpected in the differences.

> I'll add some of this info to the readme, although I'm not convinced about adding VM setup or OS installation instructions to LibreSignage docs since those might get outdated and I'd have to keep track of them too.

I gave these instructions specifically for Debian 9 and Ubuntu 18.04, respectively. As such, they should never outdate, assuming that nodejs over the PPA doesn’t break things. That is to say, as long as you don’t upgrade the OS to a later version, its updates will never change the software versions in their respective packages.

> I will include OS version information though.

You should name minimum system requirements and a reference OS.
