### ISSUE TITLE
CentOS 7 install error

### ISSUE THREAD

**Issue by samotelf** [eerotal/LibreSignage#35]
Hello. 
I'm trying to install it in CentOS 7 but it gives me this error.
Can you please help?

[root@localhost LibreSignage]# make configure
Document root (DEF: /var/www): /var/www/html
Server name (domain): localhost
Server name aliases (space separated): localhost
Admin name: home
Admin email: home
Enable debugging? (y/N): N
Write config to 'build/localhost.iconf'.
[root@localhost LibreSignage]# sudo make install
[INFO] Include dependency makefiles.
dep/app/js/main.js.dep:3: *** target pattern contains no `%'.  Stop.

**Comment by eerotal** [comment]
Could you go through this list:

1. Please check the version of make by running `make -v`.
2. What branch are you on when trying to compile? `master`, `next` or even something else.
3. Could you paste the contents of `dep/app/js/main.js.dep` here.

**Comment by eerotal** [comment]
This issue seems to be the same as issue #48, which was fixed. I'm closing this one for now. If the problem persists you can create a new issue.
