### ISSUE TITLE
control_panel.rst references missing quotas.rst

### ISSUE THREAD

**Issue by nitinthewiz** [eerotal/LibreSignage#38]
https://github.com/eerotal/LibreSignage/blob/master/src/doc/rst/control_panel.rst references a link called /doc?doc=quotas which doesn't exist.

Is that some documentation you're going to add, or did you mean to refer to the limits.rst file?

**Comment by eerotal** [comment]
I probably meant to refer to 'limits.rst'. I'll have to check it out.

**Comment by eerotal** [comment]
This is now fixed in ´next´.
