### ISSUE TITLE
Feature Request: No login display

### ISSUE THREAD

**Issue by nitinthewiz** [eerotal/LibreSignage#39]
It would be awesome to view a default display without logging in. This can still count against some sort of 'no login user' API quota.

**Comment by eerotal** [comment]
This could be a good feature to consider. I'll put it on my TODO list.

**Comment by paulfurze** [comment]
This is a real need.
Just managed to set up everything on our local server....
Damn office TV browser cant log in (JS issue I think  !!!
Please make it so that you can just goto...
//www.xxx.yyy/nologin/q=<quename>
That'd allow selection of display ques straing from things like TV's

**Comment by eerotal** [comment]
I'm planning to implement this feature or a similar solution to the problem when I get the time. Right now I'm working on a rather big overhaul of the API though, so it'll take some time.

However, I'm not sure whether a no login user will solve your problem @paulfurze . It seems like the TV web browser might not support some JS features that LibreSignage uses, which is why the login page JS might be failing. The problem here is that even if no login was required, LibreSignage would still use most of the same JS code for fetching data through the API. The authentication system is just a small part of the API interface module used in the web interface.

In fact, I once tried LibreSignage on an LG smart TV and I had similar problems. I haven't really looked into it after that though.

**Comment by paulfurze** [comment]
Yes, probably right. I started looking into a simple USB stick PC as an alternative.

**Comment by eerotal** [comment]
No problem. A small external PC is probably the simplest solution at least for now. You can also look into the Raspberry Pi if you haven't already. Those are quite nice for applications like this and AFAIK quite popular for digital signage etc.

**Comment by unquietwiki** [comment]
@eerotal @paulfurze I wish I read this bug yesterday; ran into that LG Smart TV issue too. Could https://babeljs.io/ or something be used to generate compatible JS the TVs would work with?

**Comment by nculpitt** [comment]
Hey @eerotal I just wanted to check in on if you've had any opportunity to have a look at this so far

I've implemented LibreSignage at a hospital with a screen in each ward (7 screens), and the login screen/timeout is my biggest issue in terms of ongoing management.

**Comment by eerotal** [comment]
This seems to be a prominent issue for many people so I do need to take a look at this. So far I haven't had the time as I've been working on some other big changes for v1.1.0, but I'll look into this soon.

By the way, you mentioned that some timeout is an issue. What timeout do you mean?

**Comment by nculpitt** [comment]
I think the timeout issue is likely unrelated to LibreSignage itself, I think the pi's I'm using are likely having some sort of internet issue which is making the slides go blank.

But because of the login screen, i can't just add a script to refresh the page every 30 or so minutes, if that makes sense.

**Comment by eerotal** [comment]
Ah ok. Did you select the *Start a display session* checkbox from the *Advanced settings* dropdown when logging in a client?

**Comment by nculpitt** [comment]
I have been using "Start a display session", but I'll confirm that it's definitely ticked on all of the boxes tomorrow. This might be why some of screens require more intervention than others. Thanks for looking into it! 

Definitely I still think a no login display would still be really valuable to ensure that the screens are as hands off as possible

**Comment by eerotal** [comment]
I'll try to release a new patch version of LibreSignage (v1.0.2) soon so you get the new bugfix too.

**Comment by nculpitt** [comment]
Thanks very much! We had an internet outage yesterday so I went through all the boxes to put them on a display session, then made a change to slide speeds, which somehow managed to break all the screens (quite sure this is an internet issue that I'm about to solve by running the LibreSignage docker internally on ethernet)

Refreshing them again brought them all back to the login screen, so seems that it may be related to that auth bug. Thanks again for looking into it and releasing a patch.

**Comment by eerotal** [comment]
Okay, I just released v1.0.2 that includes the authentication bugfix. It should appear in Docker Hub shortly and the source is available in the *master* branch here on GitHub.

**Comment by nculpitt** [comment]
Thanks so much for your hard work on this!

**Comment by eerotal** [comment]
No problem!

**Comment by jaumemoral** [comment]
Hi! We are evaluating this software to replace our old propietary system and it will be a must to not have a login page in display screens. We plan to use Raspberries ensuring that after a reboot we clean all cache and cookies.

**Comment by eerotal** [comment]
@jaumemoral Yeah, I need to start working on this once I have time. I just about finished another massive change I've been working for **a long** time so hopefully I can start working on some of the existing feature requests soon.

**Comment by eerotal** [comment]
Passwordless logins are now implemented in `next` to solve this issue. The web interface also includes a new URL `/app_bootstrap` for automatically logging in as a passworldess user when a browser is started. Further documentation is included in `src/doc/rst`. The changes should ship in v1.2.0.
