### ISSUE TITLE
Feature Request: button controls for slide navigation

### ISSUE THREAD

**Issue by nitinthewiz** [eerotal/LibreSignage#40]
For some instances (touch screen displays, users being able to view the slides on their computers), it would be great to have button controls on the edges that let a viewer navigate to the next or previous slides. The transition times and all would remain the same, but if the user wants, they can go back to the previous slide, or to the next one.

**Comment by eerotal** [comment]
This could indeed be a useful feature. I'll add it to my TODO list.

**Comment by eerotal** [comment]
This is now implemented in next and will be shipped in v1.1.0.
