### ISSUE TITLE
Login page doesn't reroute to requested URI

### ISSUE THREAD

**Issue by nitinthewiz** [eerotal/LibreSignage#41]
If I open the direct URI to a new queue (http://localhost/app/?q=newQueue) but I'm not logged in, I'm asked to login, but then shown the prompt for queue selection again. This is not the correct behavior - it should redirect me to the previous URI after login. Usually, the way this works is that the 'requestedURI' is part of the URL parameters.

**Comment by eerotal** [comment]
This should be quite simple to fix. I'll have a look at it

**Comment by eerotal** [comment]
This is now fixed in `next`. Closing.
