### ISSUE TITLE
Missing Libs

### ISSUE THREAD

**Issue by strikeferret** [eerotal/LibreSignage#42]
I appear to be missing /libs/@fortawesome/fontawesome-free/css/all.css (it may also cause issues  I am having logging in as well).  In fact, it doesn't appear any CSSs were installed. Since I don't see any in the repository, I assume this is due to one of the following.

- I did not install a dependency (which may or may not have been listed, I'm sorry. I'm very tired)
- This is an issue with my SSL configuration
- This is a problem with my proxy configuration
- There is an issue affecting me that's not affecting everyone else
- There's an issue that people have fixed on their own

Please advise on what I can do to troubleshoot. I'm afraid I don't understand the software enough to see where there may be an error.

XCP-NG hypervisor running an Ubuntu 18.04 fresh install from mini ISO. NPM installed through APT. dependencies installed through the instructions on the site. Downstream proxy is NGINX. (configuration works with other sites, but did take some testing to work with LibreSignage)

Thanks, I've been looking for something like this for some time, and my projects were never overly successful.

**Comment by eerotal** [comment]
The npm version in the Ubuntu repos is too old and for some reason it doesn't work with font-awesome. You need to download it from the node.js website instead.

**Comment by strikeferret** [comment]
Happy it is a simple solution but embarrassed I didn't try it myself; the documentation warned me. Thanks.
