### ISSUE TITLE
Incompatibility with Porteus Kiosk

### ISSUE THREAD

**Issue by ynl1** [eerotal/LibreSignage#46]
Hello, I am trying to use LibreSignage along with Porteus Kiosk, the only problem is that neither the login button nor the advanced dropdown menu work.
Can you please tell me what the problem is? Or at least recommend a Kiosk OS to use with LibreSignage? I'm running out of ideas.

**Comment by eerotal** [comment]
Can you check what browser Porteus Kiosk is using and what version the browser is. Also please check what LibreSignage version you're using. I have seen something similar before and concluded the browser didn't support some of the JS features used by LibreSignage, but I didn't really investigate that in any depth at the time. Technically any distro should work as long as the browser is fairly recent.

**Comment by ynl1** [comment]
Thank you for replying,

I used Google Chrome, The version Porteus Kiosk came with was Chrome 55 so it was rather outdated, I am now downloading a new version of Google Chrome to test if it works, wish me luck.

**Comment by eerotal** [comment]
That might be the problem. I usually use Chrome myself so LibreSignage **should** work on it.

**Comment by ynl1** [comment]
Something else happened, I updated porteus to the x64 version, and everything seemed to work fine, it displayed what i told it to, everything. But after 10 minutes it shows a box that says "You are not authorized to perform this action"

**Comment by eerotal** [comment]
What LibreSignage version are you using? The version number is displayed in the footer of the web interface.

**Comment by ynl1** [comment]
I'm using v0.2.2, which is strange since I cloned it using git, as the instructions on the readme said, do I have to download one of the releases?

**Comment by eerotal** [comment]
You'll need to clone the repo like you did and then checkout the `next` branch by running `git checkout next`. That way you'll get all the latest changes.

**Comment by ynl1** [comment]
Ok, I cloned the repo and ran git checkout next, and now it doesn't wanna configure nor compile. I tried specifying the target but it still doesn't work.

**Comment by eerotal** [comment]
Try running these commands

`
make realclean
make configure TARGET=apache2-debian
make -j$(nproc)
sudo make install
`
