### ISSUE TITLE
Videos are muted during slide display

### ISSUE THREAD

**Issue by infomaniac50** [eerotal/LibreSignage#47]
When I display a slide queue with a video in it, that video doesn't have any sound. When I force it to show the controls, the volume button says it muted. I can unmute it, but when the queue starts over the video is muted again. I've tried this on two machines but with only Google Chrome so far. 

Might this have something to do with Chrome's autoplay policy. https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

I'm running the server on Docker for Linux. I pulled the image from hub.docker.com ``eerotal/libresignage:v1.0.0-beta-1``.

### Host Details
```
Google Chrome	72.0.3626.121 (Official Build) (64-bit)
Revision	da3787ba355f18db7db52abf75c42afb408d656f-refs/branch-heads/3626@{#883}
OS	Linux
JavaScript	V8 7.2.502.28
Flash	32.0.0.156 /home/derek/.config/google-chrome/PepperFlash/32.0.0.156/libpepflashplayer.so
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
```

```
OS: Arch Linux x86_64
Kernel Release: 5.0.0-arch1-1-ARCH
RAM: 15918 MB
Processor Type: Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
```

```
derek@derek-sve14126cxb:~$ docker version
Client:
 Version:           18.09.3-ce
 API version:       1.39
 Go version:        go1.12
 Git commit:        774a1f4eee
 Built:             Thu Feb 28 20:38:40 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.3-ce
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.12
  Git commit:       774a1f4eee
  Built:            Thu Feb 28 20:37:49 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

### Windows Client

```
Google Chrome	72.0.3626.121 (Official Build) (64-bit) (cohort: Stable)
Revision	da3787ba355f18db7db52abf75c42afb408d656f-refs/branch-heads/3626@{#883}
OS	Windows
JavaScript	V8 7.2.502.28
Flash	32.0.0.156 C:\Users\Derek\AppData\Local\Google\Chrome\User Data\PepperFlash\32.0.0.156\pepflashplayer.dll
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
```

**Comment by eerotal** [comment]
It definitely looks like this is due to the autoplay policy but I'll have to take a closer look at the problem.

**Comment by eerotal** [comment]
I had a more in-depth look at the issue and I noticed that I had made the videos muted by default on purpose. Because that is obviously a major limitation, I implemented a new property 'muted' for the [video] tag that can be used to mute/unmute videos (da46bcb78c366afa5baf6732d511578bb7eeafe7). The property seems to work without any problems but it might be required to launch Chrome with the flags `--autoplay-policy=no-user-gesture-required --disable-features=AutoplayIgnoreWebAudio` in some cases.

**Comment by infomaniac50** [comment]
This almost certainly fixes the issue. Chrome's autoplay policy does factor in how many times you played videos on the current URL.

I tried few things to see if I could break it, but I could not. **They all played audio.**

- I tried opening the queue with the autoplay policy set to default. *The button click might be considered DOM interaction.*
- I tried loading the queue directly from the URL bar.
- I tried reloading the tab in the background by right-clicking and selecting reload.

I wondered if the videos should be un-muted by default, but it's probably best to require explicit instructions in this stage of development. Leaving stuff out using magic is a sure way to confuse people.

If you develop the markup editor further you can add defaults there. I think I saw something about a GUI editor in one of the other issues.

I tested everything using my Docker in Docker build.

**Comment by eerotal** [comment]
Okay, so the issue should be fixed now. Thanks for the comprehensive testing! Yes, there might eventually be a GUI editor but that'll certainly take a lot of time.
