### ISSUE TITLE
Readme is missing system dependency on imagemagick

### ISSUE THREAD

**Issue by infomaniac50** [eerotal/LibreSignage#49]
The issue is mostly in the title. ``convert`` is the program used to make logos and such. This program is a part of the ImageMagick suite. For most system package managers this is referenced with the package name ``imagemagick``.

I encountered this when making my Docker in Docker container to test the makefile problem over on issue #48.

The fix is to add imagemagick to the list of packages for apt install over on the readme.

**Comment by eerotal** [comment]
Ah, that's a fairly recent additon to the build system so I have forgotten it. I'll just add it to the readme, thanks.

**Comment by eerotal** [comment]
I added ImageMagick to the dependency list in the readme and I also implemented a failsafe into the build system to make sure a compatible version is installed. (64542b5161624dca4b8bfe830b480ca9a79943b6)
