### ISSUE TITLE
common/php/footer/footer_util.php does not exist

### ISSUE THREAD

**Issue by infomaniac50** [eerotal/LibreSignage#50]
https://github.com/eerotal/LibreSignage/blob/1549113a8ca4a9a907e5c146cea418d305625538/src/app/index.php#L5

footer_util.php doesn't exist anywhere. footer.php is what goes at the bottom of the page so that's not it either.

Is this a work in progress? If it hasn't been pushed yet then I'll wait to test it later.

**Comment by eerotal** [comment]
Oh, I tried something new with the footer code yesterday but apparently forgot to remove that line. It's not needed anymore so I'll just remove it.

**Comment by eerotal** [comment]
This is now fixed in f4fccd831ce718aabab8c9ee1240fbdee77b05c7.
