### ISSUE TITLE
Feature Request: Serve media files statically

### ISSUE THREAD

**Issue by infomaniac50** [eerotal/LibreSignage#53]
Media files should be served statically to enhance caching and reduce load on PHP. Right now media files are pumped through PHP without caching headers. This puts a lot of load on the network for files that probably won't change.

On slower machines like kiosks or smart TVs the network interface can put a lot of strain on an otherwise already loaded processor. Forcing each machine to download the same content over and over will cause stuttering, corrupted/dropped video frames, high network latency, and a sluggish response.

If you make the media folder publicly accessible then the web server can handle the caching. Coincidentally this allows you to serve media files from a CDN too. The PHP code will be able to handle many more requests since PHP processes are not being hold open.

**Comment by eerotal** [comment]
Caching the media files is actually a very good idea, no idea why I haven't paid any attention to that before. Making the media folder(s) public probably isn't something I want to do for a good reason:

1. Allowing direct access to the media files on the server would undermine any access control systems, which obviously is not a good thing.
2. Allowing access to a directory that contains uploaded files widens the attack surface of the server. One possible scenario is the following:
  - A malicious user manages to somehow upload a PHP file on the server (which **shouldn't** be possible, but bugs sometimes exist).
  - The user navigates to the malicious file with a browser, making the server execute the file.
  - The PHP file does something to compromise the server.
The current asset access system has some features to prevent the above scenario.

**Comment by infomaniac50** [comment]
I gathered a list of URLs that talk about HTTP caching. It might come in handy when writing a rough draft.

### Guides 
* [HTTP caching - HTTP | MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching)
* [HTTP Caching  |  Web Fundamentals  |  Google Developers](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching)
* [Caching Tutorial for Web Authors and Webmasters](https://www.mnot.net/cache_docs/)

### Symfony 
* [HTTP Cache (Symfony Docs)](https://symfony.com/doc/current/http_cache.html#http-cache-introduction)

### IETF Specifications
* [RFC 7234 - Hypertext Transfer Protocol (HTTP/1.1): Caching](https://tools.ietf.org/html/rfc7234)
* [RFC 7232 - Hypertext Transfer Protocol (HTTP/1.1): Conditional Requests](https://tools.ietf.org/html/rfc7232)

**Comment by infomaniac50** [comment]
It looks like all of the PHP code is written from scratch. Your application is very clean and organized even though you don't have any composer dependencies. [The HttpFoundation Component](https://symfony.com/doc/current/components/http_foundation.html) from Symfony already has all of this. It might be worth it to add some composer dependencies so you don't have to write everything yourself.

**Comment by eerotal** [comment]
It might be a good idea to use some dependencies but I'll have to see how they fit into the LibreSignage codebase first. I initially chose to write the API system myself so that I can easily make it just right for LibreSignage. A custom API system might be even more important now that I have been planning changes for the features requested in #36. I'm probably going to implement a server-push system for passing data to client displays to make it possible to control the clients in more detail.

**Comment by infomaniac50** [comment]
This might be something else to look at for a version 2+ build.

It does the "206 chunking", beforehand on the server. I know big content providers like Netflix serve these files statically from a CDN and they also have DRM as a sort of access control. I'm sure it probably complicated to setup though.

If you watch the Network tab in Chrome DevTools you can see .ts files being downloaded. They may not have a .ts extension but that's usually what they are. These are MPEG transport streams and they are pretty much the Internet equivalent of a Blu-ray movie. My TV tuner card exports a TS file for each subchannel in ATSC.

https://en.wikipedia.org/wiki/HTTP_Live_Streaming

> HTTP Live Streaming (also known as HLS) is an HTTP-based adaptive bitrate streaming communications protocol implemented by Apple Inc. as part of its QuickTime, Safari, OS X, and iOS software. Client implementations are also available in Microsoft Edge, Firefox and some versions of Google Chrome. Support is widespread in streaming media servers.

**Comment by eerotal** [comment]
Yeah, the video embedding/streaming could be improved quite a bit. Especially caching is something I need to look into. I'll keep your suggestions in mind.

**Comment by infomaniac50** [comment]
[The HttpFoundation Component](https://symfony.com/doc/current/components/http_foundation.html) would basically replace any code that interacts with client requests and client responses. 

The quote from Symfony says, 
> The HttpFoundation component defines an object-oriented layer for the HTTP specification.

The library is fairly large compared to your own but it's bare-bones relative to the rest of Symfony. For Symfony, the HttpFoundation component is at the core of all interaction with the outside world. Making a response can be as simple as the snippet below. 

```php
use Symfony\Component\HttpFoundation\Response;

$response = new Response(
    'Content',
    Response::HTTP_OK,
    ['content-type' => 'text/html']
);
```

Javascript API requests can be serviced by "[Creating a JSON Response](https://symfony.com/doc/current/components/http_foundation.html#creating-a-json-response)"

```php
use Symfony\Component\HttpFoundation\JsonResponse;

// if you know the data to send when creating the response
$response = new JsonResponse(['data' => 123]);

// if you don't know the data to send when creating the response
$response = new JsonResponse();
// ...
$response->setData(['data' => 123]);

// if the data to send is already encoded in JSON
$response = JsonResponse::fromJsonString('{ "data": 123 }');
```

Media responses can be serviced by BinaryFileResponse as shown in [Serving Files](https://symfony.com/doc/current/components/http_foundation.html#serving-files)

```php
use Symfony\Component\HttpFoundation\BinaryFileResponse;

$file = 'path/to/file.txt';
$response = new BinaryFileResponse($file);
```

Caching can be implemented with [Managing the HTTP Cache](https://symfony.com/doc/current/components/http_foundation.html#managing-the-http-cache)

**Comment by eerotal** [comment]
It does seem like a good solution indeed. It'd also make my work a bit easier since I wouldn't have to maintain as much API code myself.

**Comment by infomaniac50** [comment]
I'm certainly biased towards HttpFoundation since I use Symfony so much. For a custom solution it may be worth it to look at [PSR-7](https://www.php-fig.org/psr/psr-7/) and [Guzzle](http://docs.guzzlephp.org/en/stable/psr7.html). 

I don't know much about Guzzle and PSR-7 though. HttpFoundation seems similar but they don't mirror it. There is a separate bridge library for that. https://symfony.com/doc/current/components/psr7.html

Guzzle has the advantage of being compatible with any other interface that follows PSR-7. If you use dependency injection Guzzle becomes hot-swappable with any other library that implements PSR-7. See also https://packagist.org/providers/psr/http-factory-implementation

For clarity, PSR-7 is the abstraction and Guzzle is the concrete implementation. PSR-7 provides the interfaces and Guzzle provides the classes.

**Comment by eerotal** [comment]
Thanks, I have some studying to do it seems!

**Comment by infomaniac50** [comment]
Take your time. It's a big decision that affects everything that comes afterwards. It also creates a chokepoint in the commit history because of sweeping changes to the client facing code. It will definately be a v1 or above release.

**Comment by eerotal** [comment]
Okay, I have now converted the API system to use HttpFoundation and some other new dependencies. It's quite a bit nicer now. The slide asset endpoints (`slide_get_asset.php` and `slide_get_asset_thumb.php`) now support HTTP caching too, which should reduce the server load quite a bit.

I still need to tweak the web interface code a bit because HTML `<img>` tags don't seem to respect the `Cache-Control: no-cache` header that well, which makes the display page show outdated images at times.

The changes are in `next` and once finished will ship in LibreSignage v1.1.0
