### ISSUE TITLE
Restructure repository so that only public files are accessible from web root

### ISSUE THREAD

**Issue by infomaniac50** [eerotal/LibreSignage#54]
I noticed a file called include_guard.php. When I dug further I figured out it was for keeping bad browsers away from backend files. This seems like a hack and I get the feeling it is going to lead down a rabbit hole if left alone.

I've done some restructuring of the repository.  I based my changes on your next branch.

- There is a new directory called public is in the Apache html directory.
- All private files are located in the html directory. 
- All public files are located in public.
- The document root for Apache points to the public directory.

Doing it this way prevents access to private files in a natural way. It's not fully polished yet, but take a look at it. https://github.com/infomaniac50/LibreSignage/tree/restructure

Some code in the new branch is obsolete. I haven't taken the time yet to go though and delete it. include_guard.php is one example.

Addtionally, I created a graph of all static require* and include* calls. You can see the graph here https://github.com/infomaniac50/LibreSignageMetrics/blob/master/restructure.svg

- Any dynamic calls are missing because I used static analysis. 
- There are some cyclic dependencies that need to be sorted out. 
- Most of the public PHP files will have some kind of output. These public files are all at the bottom. Some of these may not be in the right place. Public PHP files shouldn't have any dependents because they are entry points. Common template code like error.php should probably be moved back to the private directory.
- At the very top is the error handler and config.php. These two files no longer have a cyclic dependency.

For testing, I went simply went through each UI element and made it perform its function. I used DevTools and Apache logs to check for errors. While testing it I discovered some new issues.

- If a queue is deleted while a slide lock is active then the lock becomes invalid. The slide unlock api call happens after the queue delete call. The unlock response shows error: 2.
- There is a missing api endpoint called user_get_quota.php. I'm not sure if this is something that is planned or simply old code. There are no calls that would crash the server so I left it alone.

There's probably other things that need to be looked over. It's way past my bedtime though so I'll come back to it later.

**Comment by infomaniac50** [comment]
> There's probably other things that need to be looked over.

I missed the unit tests.

**Comment by eerotal** [comment]
I had a quick glance and this seems like a good idea. I need to have a more in-depth look and test it later. It's nice that the public/private files are separated in your restructured version.

> If a queue is deleted while a slide lock is active then the lock becomes invalid. The slide unlock api call happens after the queue delete call.

This should be simple to fix.

> There is a missing api endpoint called user_get_quota.php. I'm not sure if this is something that is planned or simply old code.

That's an old API endpoint that was replaced by functionality in auth_get_data.php. I must've forgotten to replace the old call.

> I missed the unit tests.

LibreSignage used to have tests for API endpoints but they became so outdated I removed them from next. I've been planning to write proper API and PHP unit tests from scratch though.

**Comment by infomaniac50** [comment]
> > I missed the unit tests.
> 
> LibreSignage used to have tests for API endpoints but they became so outdated I removed them from next. I've been planning to write proper API and PHP unit tests from scratch though.

No wonder I missed them. I use the OctoTree extension for Chrome and it's only shows the master branch when I browsing issues. I saw the utests/api and thought I had more work to do.

**Comment by eerotal** [comment]
It might take some time until I can test this because I'm focusing on #52 right now. I'll get around to testing this one eventually though!

**Comment by eerotal** [comment]
Right, I had a more in-depth look and this seems like a really good change! The include_guard.php thing is definitely a hacky way of preventing access to private files. In fact, I didn't even remember I had written something like that. By all means, make all the changes you intended and put your finishing touches on it.

When you make all of your changes in your own branch you can create a pull request so that I can have another look at the finished changeset and then merge it. I think I'll include this in the next minor release if you get it ready by then. Also, remember to rebase your branch on next at least before creating the PR so that merging is a bit less painful. Rebasing something like this is probably a bit annoying when files are moved around etc. but I think it's easier to do it now instead of trying to fix merge conflicts later.

**Comment by eerotal** [comment]
I'll close this now that you created the PR.
