### ISSUE TITLE
When reading the documentation on Github, the link to the Markup page is wrong

### ISSUE THREAD

**Issue by Revisor** [eerotal/LibreSignage#63]
Hello,
I'm reading this page: https://github.com/eerotal/LibreSignage/blob/master/src/doc/rst/editor.rst
The link under "LibreSignage Markup" leads to a 404 page.
I found the Markup documentation here: https://github.com/eerotal/LibreSignage/blob/master/src/doc/rst/markup.rst

I know the doc directory is used to build a documentation for the installation, but maybe it would be possible to make the links work on Github, too?

Anyway, you've done good work, congratulations for the 1.0 release.

**Comment by eerotal** [comment]
Yeah, I'm aware of this issue but it's really not something that can be easily solved. If I create a website for LibreSignage I'll put the docs there and fix the links but for now you'll need to find the files manually. Thanks!
