### ISSUE TITLE
No Balena Cloud Support

### ISSUE THREAD

**Issue by JeffResc** [eerotal/LibreSignage#64]
Although [Balena Cloud](http://balena-cloud.com) natively supports Docker and Dockerfiles, it does not seem to work out of the box. Balena can be very helpful as it allows me to deply a fleet of digital menu boards and update/manage them all from a central location. I would really apperciate if Balena Cloud support was added to LibreSignage.

**Comment by eerotal** [comment]
I'm not really sure why you'd need this though, since LibreSignage basically is a central server already. You don't need to deploy it on clients at all. Clients only need to have a web browser that connects to the server to show content.

If there is a use case with Balena Cloud then sure, it could be considered. This is the first time I've heard of it though, so someone more familiar should probably make the required changes.

**Comment by JeffResc** [comment]
My biggest issue is that my digital signage resides on a network where all inbound connections are blocked due to security reasons with no exceptions allowed. Balena is basically a central control allowing me to remotely access the terminal, review logs and use power controls like shutdown or restart. Not to mention that it provisions the devices so the install process only has to happen once.

**Comment by eerotal** [comment]
Ah ok. Why doesn't LibreSignage work with Balena Cloud then? I have no idea of the general workflow used when deploying apps with Balena Cloud so I have no idea why it might be failing.

**Comment by JeffResc** [comment]
There are a few errors I encounted. Right off the bat, there’s no way to specify variables in the cli like docroot, so I had to specify those directly in the Dockerfile. Then, the copy command didn’t support `--chown`. After that, all of the sudo commands had to be changed as Balena is automatically root. I’m starting to think this might be more work than it’s worth.

**Comment by eerotal** [comment]
And if I'm not mistaken, Balena doesn't seem to support running the makefiles used to build LibreSignage. The way LibreSignage is built is 

1. Build the distribution using make etc.
2. Build the docker image from the prebuilt files separately.

It might require quite a few changes to the build system to make LibreSignage work on Balena, but I or someone else might take a look at it eventually.

**Comment by eerotal** [comment]
I don't think this is something I am interested in working on at this time so I'm marking the issue wontfix and closing it. If someone else wants to work on this that's cool of course.
