### ISSUE TITLE
v1.0.0 Debian source install -> 500 Internal Server Error

### ISSUE THREAD

**Issue by lausvi** [eerotal/LibreSignage#65]
Hi, 
I used to be able to install and run LibreSignage in my LXC container (running Debian 9), but the new 1.0.0 version does not install succesfully per the "4.3.1 Building a native build on Debian or Ubuntu" instructions. 

I get no errors during installation, but when I try to access the web interface, I get "500 Internal Server Error", but with the LibreSignage styling and copyrights on the bottom of the page (and it redirects to /control/) so it's installed but it's having some other issue. Apache logs don't show anything, how should I proceed on troubleshooting this?

**Comment by eerotal** [comment]
First you could enable debugging when you run ``make configure``. That way you should get more detailed error messages when loading the web interface.

I might know the problem already though, I think the Debian 9 repos contain a PHP version that's too old. The readme probably has outdated version requirements for PHP but LibreSignage v1.0.0 requires PHP 7.1 or newer.

**Comment by lausvi** [comment]
Thanks!

Updating to PHP 7.3 did not help, here's what the enable debugging now throws at me:

### Uncaught exception (HTTP: 500) ###
TypeError: Return value of ls_log_enable() must be an instance of void, none returned in /var/www/localhost/common/php/log.php:20
Stack trace:
#0 /var/www/localhost/common/php/error.php(38): ls_log_enable(true)
#1 /var/www/localhost/common/php/config.php(74): error_set_debug(true)
#2 /var/www/localhost/control/index.php(2): require_once('/var/www/localh...')
#3 {main}<br />
<b>Fatal error</b>:  Uncaught TypeError: Return value of ls_log_close() must be an instance of void, none returned in /var/www/localhost/common/php/log.php:55
Stack trace:
#0 /var/www/localhost/common/php/log.php(99): ls_log_close(Resource id #5)
#1 /var/www/localhost/common/php/error.php(80): ls_log('TypeError: Retu...', '/var/log/libres...')
#2 /var/www/localhost/common/php/error.php(55): error_handle(500, Object(TypeError))
#3 [internal function]: {closure}(Object(TypeError))
#4 {main}
  thrown in <b>/var/www/localhost/common/php/log.php</b> on line <b>55</b><br />

**Comment by eerotal** [comment]
This still looks like what would be thrown when the void return type is not supported. Are you sure apache2 is actually using the newer PHP 7.3 instead of 7.0? If both are installed, I think you need to run something like the following:

```
sudo a2dismod php7.0
sudo a2enmod php7.3
```

**Comment by lausvi** [comment]
Thanks, it was indeed old PHP still running, and running those two commands fixed it!
