### ISSUE TITLE
Incorrect markup breaks the editor

### ISSUE THREAD

**Issue by lausvi** [eerotal/LibreSignage#66]
I found a way to break the editor into a state where you can't change queues or edit any of the slides therein.

Starting with a fresh installation of 1.0.0:
- edit any of the example slides
- paste in any url into a p -tag
- save slide
- now the preview of the slide goes blank and you can't change queues etc.

I already did this twice by accident! Couldn't fix it other than doing a fresh install.

**Comment by eerotal** [comment]
That's... Unexpected. Are there any errors in the developer console of your browser?

**Comment by lausvi** [comment]
TypeError: rule is undefined[Learn More -> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Unexpected_type?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default]

main.js:32160:1

**Comment by eerotal** [comment]
This issue should now be fixed. The bugfix will ship in v1.0.1. There was a bug in the markup parser where the parser didn't know what to do with forward slashes outside closing tags, which caused exceptions to be thrown.

Now forward slashes in literals, ie. inside tags, cause a properly handled unexpected token error unless they are escaped. This matches the behaviour of other special characters: You'll need to escape the following characters with a backward slash when used in tags: ``=, ', ", [, ], /, \``. Even URLs should now work when properly escaped :)
