### ISSUE TITLE
Buttons do not work in Firefox and Chromium

### ISSUE THREAD

**Issue by boschkundendienst** [eerotal/LibreSignage#70]
Hi,
first of all, many thanks for starting this project. I did a quick test with docker:

```
docker run -d -p 80:80 --mount source=ls_vol,target=/var/www/html/data eerotal/libresignage:v1.0.0
and
docker run -d -p 80:80 --mount source=ls_vol,target=/var/www/html/data eerotal/libresignage:v1.0.0
```
Connecting to 127.0.0.1:3000 no issue but I am not able to upload images or use the editor in a normal way. I tested with latest Firefox and Chromium. Sometimes buttons work, sometimes they don't.  Maybe you test with some other browser?

In general I find the interface and layout very promising and good looking. I don't know if I am doing anything wrong on my side but at this point I could not even create a test slide with an uploaded image because buttons only work from time to time.

Keep going and thanks.

Regards

Peter

**Comment by eerotal** [comment]
I do test with both Chromium and Firefox so this is definitely odd. Could you paste what's printed in the Developer Console of the browser after clicking some buttons that don't work?

**Comment by boschkundendienst** [comment]
Sorry man, I tried.
Login -> Editor -> select default queue --> click add slide button
menu in new slide --> add media -> Browse (nothing)

Ok, then I saved the slide I could at least upload an image but could not find out how to use it. Maybe I am totally crazy but I tried my best. Additionally after saving and do a preview I see an empty slide (white).

I am not very familiar with the developer tools in the browsers. If you can tell me how to monitor/log a session I could maybe do that tomorrow. Maybe what I think is intuitive is wrong and I click wrong buttons?

Regards

Peter

**Comment by eerotal** [comment]
It's totally ok, I could improve the docs a bit too. So it seems the buttons do work after all, is that correct?

- If you were able to upload an image you need to write the markup that makes the image visible in the slide. First, you need to open the media uploading dialog again and click the image you uploaded in the file list. The URL for that image will appear in the textbox below the list. Copy the URL.
- Then you can write the following markup into the Markup text field:
```
[video url="(Paste the URL here)" width=100% height=100% muted=0][/video]
```

Now you can save the slide and the image should display fullscreen.

**Comment by boschkundendienst** [comment]
main.js:30159 APIInterface: Init session renewal loop. (580s)
main.js:30183 APIInterface: Renew session.
main.js:32780 Slide: Fetch '1'.
main.js:32780 Slide: Fetch '2'.
main.js:32780 Slide: Fetch '3'.
main.js:32780 Slide: Fetch '3acdafc7db50fe32803850a92f45f81b'.
main.js:8812 Uncaught (in promise) Error: Syntax error, unrecognized expression: # This is a test<video src="http://127.0.0.1/api/endpoint/slide/asset/slide_get_asset.php?id=3acdafc7db50fe32803850a92f45f81b&amp;name=like-us-on-facebook5.png" style="display: block; width: 100vw; height: 100%;" autoplay ></video>
    at Function.Sizzle.error (main.js:8812)
    at Sizzle.tokenize (main.js:9468)
    at Sizzle.select (main.js:9895)
    at Function.Sizzle [as find] (main.js:8114)
    at jQuery.fn.init.find (main.js:10148)
    at new jQuery.fn.init (main.js:10258)
    at jQuery (main.js:7404)
    at Preview.render (main.js:27621)
    at Timeline.show_queue (main.js:27986)
    at async EditorView.show_queue (main.js:29155)
Sizzle.error @ main.js:8812
Sizzle.tokenize @ main.js:9468
Sizzle.select @ main.js:9895
Sizzle @ main.js:8114
find @ main.js:10148
jQuery.fn.init @ main.js:10258
jQuery @ main.js:7404
render @ main.js:27621
show_queue @ main.js:27986
Promise.catch (async)
(anonymous) @ main.js:33215
dispatch @ main.js:12489
elemData.handle @ main.js:12296
trigger @ main.js:15723
(anonymous) @ main.js:15801
each @ main.js:7619
each @ main.js:7454
trigger @ main.js:15800
trigger @ main.js:27896
select_queue @ main.js:27834
component.dropselect.select @ main.js:27696
(anonymous) @ main.js:33211
dispatch @ main.js:12489
elemData.handle @ main.js:12296
trigger @ main.js:15723
(anonymous) @ main.js:15801
each @ main.js:7619
each @ main.js:7454
trigger @ main.js:15800
trigger @ main.js:30828
select @ main.js:30817
(anonymous) @ main.js:30783
dispatch @ main.js:12489
elemData.handle @ main.js:12296

**Comment by boschkundendienst** [comment]
```
main.js:8812 Uncaught (in promise) Error: Syntax error, unrecognized expression: # This is a test<video src="http://127.0.0.1/api/endpoint/slide/asset/slide_get_asset.php?id=3acdafc7db50fe32803850a92f45f81b&amp;name=like-us-on-facebook5.png" style="display: block; width: 100vw; height: 100%;" autoplay ></video>
    at Function.Sizzle.error (main.js:8812)
    at Sizzle.tokenize (main.js:9468)
    at Sizzle.select (main.js:9895)
    at Function.Sizzle [as find] (main.js:8114)
    at jQuery.fn.init.find (main.js:10148)
    at new jQuery.fn.init (main.js:10258)
    at jQuery (main.js:7404)
    at Preview.render (main.js:27621)
    at Timeline.show_queue (main.js:27986)
    at async EditorView.show_queue (main.js:29155)
Sizzle.error @ main.js:8812
Sizzle.tokenize @ main.js:9468
Sizzle.select @ main.js:9895
Sizzle @ main.js:8114
find @ main.js:10148
jQuery.fn.init @ main.js:10258
jQuery @ main.js:7404
render @ main.js:27621
show_queue @ main.js:27986
Promise.catch (async)
(anonymous) @ main.js:33215
dispatch @ main.js:12489
elemData.handle @ main.js:12296
trigger @ main.js:15723
(anonymous) @ main.js:15801
each @ main.js:7619
each @ main.js:7454
trigger @ main.js:15800
trigger @ main.js:27896
select_queue @ main.js:27834
component.dropselect.select @ main.js:27696
(anonymous) @ main.js:33211
dispatch @ main.js:12489
elemData.handle @ main.js:12296
trigger @ main.js:15723
(anonymous) @ main.js:15801
each @ main.js:7619
each @ main.js:7454
trigger @ main.js:15800
trigger @ main.js:30828
select @ main.js:30817
(anonymous) @ main.js:30783
dispatch @ main.js:12489
elemData.handle @ main.js:12296
```

**Comment by eerotal** [comment]
It seems like this is a bug with the markup transpiler cause dy the "# This is a test' line. The LibreSignage markup doesn't support commenta at the moment, although this error should still be handled. Please try removing the line.

**Comment by boschkundendienst** [comment]
Hi again,
I retried today and at least could get it working. As a matter of fact, anything which is not a markup tag produces errors and therefor messes up things. For a 1.0.0 maybe not so good. Anyway will close this issue and will recheck the project in some weeks when it is 2.0.0 and ready for prime time.

Regards

Peter
