### ISSUE TITLE
Issue selecting queues

### ISSUE THREAD

**Issue by bandicootdancing** [eerotal/LibreSignage#72]
This is a bit hard to explain but I'm running into an issue selecting queues after adding and editing slides to both. I was able to select the first but couldn't select the second. It just kept toggling back to the queue tab. Logged out, restarted Apache and still wasn't able to select the second queue. I was able to ssh into the box and delete the queue. I made a second queue to replace the one I had deleted but then it happened to the original. Ended up deleting both through ssh. I'm back at one queue and everything seems to be working again. Both times I made new slides and uploaded media. 

I'm not very good with docker but I may switch to that if this happens again as I haven't had this issue at all testing the last couple weeks.

**Comment by eerotal** [comment]
I will take a look at this probably later this week. Meanwhile, could you write up the detailed steps you did in order to reproduce the bug?

**Comment by bandicootdancing** [comment]
Here are the steps I took. Not sure how much it will help but I'll add more if I run into the issue again. Just for background I deleted the default queue as soon as LibreSignage was setup. I then made a production queue (A) and a testing queue (B).

A. Add slide to queue B
B. Use media upload feature
C. Switch to queue A to copy template from slide
D. Switch back to queue B
E. Paste template in new slide.
F. Save slide

From here I was no longer able to view queue B. I could select queue A from the drop down but couldn't select queue B. After this I logged into the box using ssh and deleted queue B. I could still view and edit queue A. Then I performed these steps.

A. Create new queue C
B. Create new slide
C. Use media upload feature
D. Switch to queue A to copy templates
E. Switch to queue C to paste in slide
F. Save slide
G. Got locked in queue tab. Selecting queue A or C from the drop down did nothing.

I deleted both A and C using ssh and started over. I have a docker instance I've been testing so I copied the slide templates from there and stuck with a single queue on the machine I'm trying to deploy.

**Comment by eerotal** [comment]
I can't seem to reproduce this bug. Does this happen every time you go through these steps or is it intermittent? If you manage to reproduce this bug, please check whether there are any errors in the web browser's developer console. Also, please check the LibreSignage version you're on from the web interface footer and paste that here.

**Comment by bandicootdancing** [comment]
Sorry for the late response. Haven't had the issue until today. It looks like it might be happening when I paste a link into the editor without any proper code. I saved a media link as a placeholder while I went back to another slide to copy the code format. Now when I try selecting the queue I can't select it. When logging in it displays 11/30 slides but when going into editor I can no longer select the queue.

**Comment by eerotal** [comment]
That sounds like issue #66 which is fixed in the upcoming v1.0.1 patch relese. There were some bugs in the markup parsing code that broke the editor if specific characters were used.

**Comment by bandicootdancing** [comment]
Thanks, it looks like that is the issue after all. I was able to manually delete the slide and remove from the queue. Once it was removed I was able to select the queue and edit the slides again.

**Comment by eerotal** [comment]
Great! I'll close this issue but if you have any problems regarding this issue once v1.0.1 is released you can either reopen this issue or create a new one.
