### ISSUE TITLE
Docker add latest-tag

### ISSUE THREAD

**Issue by JasperKuiper** [eerotal/LibreSignage#73]
On Docker Hub, the stated syntax is 

`docker pull eerotal/libresignage`

However, that command returns

> Using default tag: latest
> Error response from daemon: manifest for eerotal/libresignage:latest not found

Not a major inconvience, your documentation (on Github not Docker Hub) notes to state the [version], but not having to check which version to use is a little more user friendly. I'd also recommend using this as default in documentation.

When tagging the docker image before push, just add `eerotal/libresignage:latest` to the command.

**Comment by eerotal** [comment]
I'll fix this by tagging new builds with latest and the actual version. Preserving the version number tag aswell is a good idea just so that old versions can also be pulled if needed.

**Comment by eerotal** [comment]
This is now fixed in v1.x.x and next. The fix will ship in the v1.0.1 patch release.
