### ISSUE TITLE
Feature Request: Set background color and/or image

### ISSUE THREAD

**Issue by JasperKuiper** [eerotal/LibreSignage#75]
Current slide design features only one 'layer' ontop of white canvas. 

1. Add option to set background color of canvas.
2. Add option to set a background image (per slide)
3. Add option to set default background image for all slides (only if no background image was set before)

**Comment by eerotal** [comment]
1. Changing background colors is something I've been meaning to implement. I need to look into it sometime.
2. I can certainly implement background images aswell.
3. This will be solved when the features described in #28 are implemented.

**Comment by eerotal** [comment]
I implemented two new tags: `[bgimg]` for changing background images and `[bgcolor]` for changing the background color. These tags will ship in v1.1.0 but they are already merged in next and included in nightly Docker builds if you want to give them a try.
