### ISSUE TITLE
Feature request: live agenda

### ISSUE THREAD

**Issue by JonnyTech** [eerotal/LibreSignage#77]
Is it possible to create an list of times and events then get the signage to refresh every minute to keep the display up to date. We have some meeting rooms at our charity that get booked for various events. Currently we have a static image showing what is in each room at the time. But an agenda would be better. Example:

Now - 10:00 - Discussion
10:00 - 11:00 - Meeting 
11:00 - 12:00 - Review
12:00 - 13:00 - Lunch 
etc

The list would keep updating and change automatically at the required times.

**Comment by eerotal** [comment]
There is a way to schedule slides for a specific time. You can just have all the slides in one queue and have only one of them enabled at a time. Display clients update queues periodically, so any changes are automatically fetched from the server. Queues aren't updated every minute but quite often anyway. I think the update interval is 10 minutes. Is this what you meant?

**Comment by JonnyTech** [comment]
Kinda. The main thing is having the all times and events in one list, that way someone can update just that seperate list and the signage can evaluate the list and display the correct text on screen.

So with the above example, at 11:00 the display would stop showing the previous events and show "Now - 12:00 - Review" plus the rest of the list without anyone having to make a new slide. The same list is used and no one has to make a series of slides.

The ladies at the charity are not technical and even struggle with creating stuff from a simple template. I am thinking of the simplest way to achieve the solution with the minimum of time and input from them.

**Comment by eerotal** [comment]
Ah that is unfortunately not supported out of the box but it'd definitely be possible via the LibreSignage API. I don't think it's really worth it to include such functionality in LibreSignage itself since it's probably not something most people would use. However, if you know JavaScript you could write a program that does exactly what you are looking for.

**Comment by JonnyTech** [comment]
Cool, thanks, something for me to investigate. Is there a copy of the API documentation to study? And some example projects that include javascript?

**Comment by eerotal** [comment]
Docs for API endpoints are inclueded in the PHP source files. The endpoint files are in `src/api/endpoint` or if you're viewing the next branch then it's `src/public/api/endpoint`. The docs are also compiled into HTML versions that can be viewed in the LibreSignage web interface.

I'd recommend you use the JavaScript API library used by LibreSignage itself from `src/node_modules/ls-api`. The library is a node.js package and also works standalone in node. It makes authentication and calling endpoints quite simple.

Right now there are no example projects but you can obviously check some of the LibreSignage web interface JS files for a working example. The general procedure is as follows:

- Import the required modules:
```
var APIInterface = require("ls-api").APIInterface;
var APIEndpoints = require("ls-api").APIEndpoints;
```

- Create a new APIInterface object with eg. `let API = new APIInterface("<server hostname>");`
- Init the APIInterface: `await API.init();`
- Login with `await API.login("user", "pass", false);`
- Call endpoints with `await API.call(endpoint, data);`. 'endpoint' is one of the endpoints from the imported module APIEndpoints. 'data' is the data object to send to the server.

**Comment by JonnyTech** [comment]
Wow, that is a lot to take in! Thanks for the detailed explanation. Looks like I have a lot to learn to accomplish my goal (I am not a programmer but can muddle my way through).

Does the code go into the LibreSignage editor markup window or elsewhere? Once I get it installed and working on my Debian system then I shall ask less questions - promise.

**Comment by eerotal** [comment]
You'll need to write an external JavaScript node.js program to do what you want. Basically you bypass the web interface completely and access the bare API from the external program to create the slides.

It might not be the simplest thing to do but once you figure out how to set everything up it's really quite straightforward. Questions are ok, I'm happy to help if you get stuck.

**Comment by JonnyTech** [comment]
Lastly (I hope), where are the .js files placed and how does one call them?

**Comment by eerotal** [comment]
1. Build LibreSignage on your system by following the instructions in the readme. If you want to use the Docker images instead, at least clone the LibreSignage repo and install npm and node.js. They are needed later.
2. Create a directory for your project, let's use `lsagenda` for example. Move into the new directory. Run `npm init`. Answer the questions asked by `npm init`.
3. Open `package.json` with your text editor of choice and add the following field into it but replace
[LibreSignage_repo] with the path where you cloned LibreSignage.
```
"dependencies": {
    "xmlhttprequest": "^1.8.0",
    "ls-api": "file:[LibreSignage_repo]/src/node_modules/ls-api",
    "ls-assert": "file:[LibreSignage_repo]/src/node_modules/ls-assert",
    "ls-cookie": "file:[LibreSignage_repo]/src/node_modules/ls-cookie",
    "ls-user": "file:[LibreSignage_repo]/src/node_modules/ls-user"
}
```
4. Run `npm install`.
5. Create a new directory `src` and move into it.
6. Open a new file `index.js` with you text editor and import the required modules:
```
var APIInterface = require("ls-api").APIInterface;
var APIEndpoints = require("ls-api").APIEndpoints;
```
7. Start writing code.

**Comment by JonnyTech** [comment]
Whoa, I never would have worked all that out by myself. Many thanks :)

**Comment by eerotal** [comment]
No problem :)
