### ISSUE TITLE
Implement Image

### ISSUE THREAD

**Issue by spixility** [eerotal/LibreSignage#78]
Hi,
i tryied to implement a simply image but i cant't get it to work with the markup [img url=<URL> width=<width> height=<height>][/img].

I copied the link of a picture i uploaded and paste it to the URL.

I even get errors like this: >> Unexpected token: '/'. Expected ']' (@ 0:14)

Could you show an example of an image implementation?

Best regards,
Sascha

**Comment by eerotal** [comment]
The correct syntax is

```
[img url="URL HERE" width=50% height=50%][/img]
```

One thing you need to rememvber is to escape special characters in the URL (there's actually a fix for this in the next patch), which means you must add a \ character before each special char. Some special chars include[, ] and /. If your URL is `http://example.com/images/img.png` you'll need to write it like this: `http:\/\/example.com\/images\/img.png`.
