### ISSUE TITLE
[question] iFrames possible

### ISSUE THREAD

**Issue by astrakid** [eerotal/LibreSignage#79]
Hi,
would it be possible to integrate iframes? I would like to link another page (a dashboard) into libresignage.

regards,
andre

**Comment by eerotal** [comment]
Unfortunately this is not possible in current versions. Seems like a good idea though, I'll put it on my TODO list.

**Comment by astrakid** [comment]
Great, thanks!

**Comment by munterkalmsteiner** [comment]
Is this feature currently worked on or scheduled for a particular milestone? The possibility to integrate content from external web-pages would be awesome!

**Comment by eerotal** [comment]
I'm not working on this one right now but I'll look into it at some point. It'd definitely be a good feature.

**Comment by munterkalmsteiner** [comment]
I could give this feature a shot, if it does not require extensive time and knowledge. Looking at the code, my first step would be to implement the tag in `eval_defs.js` in module `ls-markup`. Is there anything else (besides docs and tests) I would need to consider?

**Comment by eerotal** [comment]
Sure, give it a shot. You already figured out everything you need to do aswell. It should be quite a simple patch. There's no automated tests for that part of the code yet though, so you don't need to worry about those either.

**Comment by jaumemoral** [comment]
Hi. I needed also this feature and I've patched the Docker image just to test. it works without problems and I'll made a pull request ASAP

**Comment by jaumemoral** [comment]
As I promised, this is the pulls request that solves this feature https://github.com/eerotal/LibreSignage/pull/105
