### ISSUE TITLE
[Build Issue] Cannot perform SVG -> PNG icon step on Debian 10

### ISSUE THREAD

**Issue by unquietwiki** [eerotal/LibreSignage#87]
Regardless of using Imagemagick 6 (distro) or 7 (compiled), the make step for SVG-PNG icon creation has to be disabled to complete build installation. Appears to occur on latest release + HEAD.

**Comment by eerotal** [comment]
This is already fixed in the latest beta (v1.1.0-beta-1) and in next by f26f089095887794e3f2dbf7d8b09a8ce8db3ab7.
