### ISSUE TITLE
[BUG] Login not working

### ISSUE THREAD

**Issue by nikolicjakov** [eerotal/LibreSignage#90]
Hi everyone, i would like to report to you that login is not working.

I have tested deploying with docker image from dockerhub behind proxy server and directly on host IP without proxy in front.

I have tested it with docker tags 'latest' and 'nightly' in any case login is not working.
Here is the SS of the error message that i am getting in Chrome console..

![Screen Shot 2019-09-23 at 13 05 19](https://user-images.githubusercontent.com/10121208/65421019-eed8d780-de02-11e9-8c04-ae046a987b70.png)

I have internal DNS server running and domain 'tv.intra.net' registered to point to my host server.
Am i doing something wrong or there is a bug in your code??

**Comment by eerotal** [comment]
Interesting. The message in your console indicates there's an internal server error. I can't reproduce this on my system though. I have even run LibreSignage behind a reverse proxy before and it worked fine.

What command did you run to start the Docker container? Are you running any script blocker extensions in your browser?

**Comment by nikolicjakov** [comment]
Hi @eerotal ,

it looks like application is working fine if it is hosted on "localhost" address. But if you host it behind another domain like "for.example.io" then login is not working.

I am running it with following command:

`docker run -d --name=tv --restart=unless-stopped -p 80:80 -v /home/tv-data:/var/www/html/data eerotal/libresignage:latest`

**Comment by eerotal** [comment]
The problem seems to be with using bind mounts. When you bind mount a directory to `/var/www/html/data` inside the container, you remove all the existing data and that's what makes LibreSignage fail. You should use Docker volumes instead by replacing the `-v ` flag with eg. `--mount source=ls_vol,target=/var/www/html/data`

**Comment by nikolicjakov** [comment]
Ok this seems to be the case, i was thinking that data folder is empty and once i create slides they get stored in this directory but i might have been wrong.

Thanks for help and i hope that you plan to add ability to showcase website since we have stats on Grafana that we would like to display and Jenkins pipelines also.

But it looks like this project has future and i like it so far.
