### ISSUE TITLE
Login possible, but in the editor no symbols in the buttons

### ISSUE THREAD

**Issue by lutzehlers** [eerotal/LibreSignage#92]
Hello eero,
first, you made a good Job.
i have installed libresignage on ubuntu 18.04.3 lts. the dependecies are:
php = 7.2
Apache = 2.4.29
make = 4.1.9
doxygen = 1.8.13
git = 2.17.1
ffmpeg = 3.4.6
php-xml = 7.2+60
php-gd = 7.2+60
pandoc = 2.7.3
curl = 7.5.8
npm = 6.4.1
nodejs = 10.17
ace-builds = 1.4.7
bootstrap = 4.3.1
jquery = 3.4.1
Popper.js = 1.16.0
fontawesome = 5.11.3
rsvg-convert = 2.4.4
librsvg = 2.4.4
imagemagick = 6.9.7
i can´t see or klick the Buttons to edit any slides.name, owner, Duration aso is Grey marked. create a new user is possible. can u fix that? or have an idea?
best regards from Germany
lutz

**Comment by eerotal** [comment]
Did you select a queue from the blue dropdown box on the left first and then try to select a slise from the timeline. The some editing controls shoule become enabled when you select a queue

**Comment by lutzehlers** [comment]
so, i´ve tested it now. it´s possible to create a new Queue and a new slide, but there no Symbols in the red, green or blue Buttons:-(
the Tooltip is showing the function.

**Comment by eerotal** [comment]
Ah okay. What version of LibreSignage are you using? You can see the version number in the footer of the web interface. What browser are you using? Could you check whether there are any errors in  the developer console of your browser so I have a bit more information to work with?

**Comment by lutzehlers** [comment]
i use the 1.0.1-dirty version. i´ve tested ff, chrome, chromium and Edge all have the same problem. i can´t see/find any Errors in the developer console...

**Comment by lutzehlers** [comment]
ah, also i can´t close the add media window ...the white cross in the Right Corner is not visible

**Comment by lutzehlers** [comment]
![Screenshot_2019-11-02 LibreSignage Editor](https://user-images.githubusercontent.com/57234739/68068768-12bfff00-fd59-11e9-8f23-10e01eb58a71.png)

**Comment by lutzehlers** [comment]
that´s a actually screenshot...hope, u can see the faults?

**Comment by eerotal** [comment]
I just noticed you said in the first message that you have Font-Awesome 5.11.3 installed, but such a version of Font-Awesome is not even released. The problems you are seeing also look like there's a problem with the Font-Awesome dependency, since no icons work. The latest, and correct, version is 5.11.2. Did you install the NPM dependencies by just running `npm install`?

**Comment by lutzehlers** [comment]
@hallo eerotal,
ich habe jetzt noch einmal einen server ubuntu 18.04 lts ohne desktop aufgesetzt (VM). jetzt sind die icons alle zu sehen👍aber wie kann ich auf die version 1.1 0 updaten?

**Comment by eerotal** [comment]
Sorry I don't speak German, but if I translated correctly, you got LibreSignage working. Great! You probably shouldn't upgrade to version 1.1.0 yet since the stable version hasn't been release yet. There's only a beta (v1.1.0-beta-1) available. Once I get everything finished, I'll release v1.1.0 here on GitHub and then you can either clone it from the master branch or use the automatically updated Docker images from Docker Hub.

If, however, you still want to try out v1.1.0-beta-1, you can pull it from the *next* branch and build & install it using the (updated!) instructions in the readme. Again, I don't recommend this version for normal production use.

**Comment by lutzehlers** [comment]
ok, my fault to send it in german:-) but u translate it correct.
so, i will wait with update since you´re release itat least one question about usebility: how can migrate an image into the slide? have u got an example for me? and is it only possible to slide an image instead permanently show on the display?
best regards lutz

**Comment by eerotal** [comment]
You can embed images in slides by using the `[img]` tag. The syntax is `[img url=<URL> width=<width> height=<height>][/img]`. You should replace *<URL>* with the URL of your image. You can copy the URL from the LibreSignage media uploader popup or from the internet. You should also replace *<width>* and *<height>* with some dimensions. The dimensions are specified as a percentage of the display size, ie. specifying 50% as the width sets the image to 50% of the width of the display.

If you want to only show one image permanently, you can create a queue with only one slide and just add the image to the slide with a width and height of 100%. Then you can set the slide animation to *No animation* and the client should only show the image you specified indefinitely.

**Comment by lutzehlers** [comment]
thx for the description...
i tried just this: [img url=http://signage/api/endpoint/slide/asset/slide_get_asset_thumb.php?id=1&name=Screenshot_2019-11-02%20LibreSignage%20Editor.png width=100% height=100%][/img]
and the editor marked the line in red and at bottom shows this: >> Unexpected token: '/'. Expected ']' (@ 5:14)
do u know why? is it my fault?

**Comment by eerotal** [comment]
Ah, I forgot to mention you'll have to surround the URL with quotes like so:
`[img url="http://signage/api/endpoint/slide/asset/slide_get_asset_thumb.php?id=1&name=Screenshot_2019-11-02%20LibreSignage%20Editor.png" width=100% height=100%][/img]` That should make it work :)

**Comment by lutzehlers** [comment]
So, now it works perfect...many thx for that...

**Comment by eerotal** [comment]
Great!
